const DISCLAIMER = "互动估算，不构成专业建议。";

const p = (id, label, unit, min, max, step, defaultValue) => ({
  id, label, unit, min, max, step, default: defaultValue,
});

const m = (id, label, output, format = "number", unit = "") => ({
  id, label, output, format, unit,
});

const explanation = (formula, assumptions, boundary) => ({
  formula, assumptions, boundary, disclaimer: DISCLAIMER,
});

const chart = (type, modes, xLabel, yLabel, series = ["value"]) => ({
  type, modes, xLabel, yLabel, series,
});

const library = [
  // 生活日常
  {
    version: 1,
    id: "caffeine-decay",
    title: "咖啡因还剩多少？",
    category: "生活日常",
    question: "下午喝咖啡，晚上体内还剩多少咖啡因？",
    modelType: "decay",
    parameters: [
      p("initial", "摄入量", "mg", 20, 500, 10, 200),
      p("halfLife", "半衰期", "小时", 2, 10, 0.5, 5),
      p("duration", "观察时长", "小时", 4, 24, 1, 12),
    ],
    metrics: [
      m("remaining", "最终剩余", "finalValue", "number", "mg"),
      m("remaining-percent", "剩余比例", "percentRemaining", "percent"),
    ],
    chart: chart("area", ["area", "line", "step", "bar"], "小时", "咖啡因 mg"),
    explanation: explanation(
      "剩余量 = 初始摄入量 × 0.5^(经过时间 ÷ 半衰期)",
      ["按固定半衰期估算", "个体代谢速度可能明显不同"],
      "仅用于理解指数衰减，不用于医疗判断。",
    ),
    keywords: ["咖啡", "咖啡因", "半衰期", "代谢", "晚上", "摄入"],
    source: "builtin",
    featured: true,
  },
  {
    version: 1,
    id: "sleep-debt",
    title: "睡眠债累积",
    category: "生活日常",
    question: "每天少睡一点，一周会积累多少睡眠债？",
    modelType: "linear",
    parameters: [
      p("initial", "已有睡眠债", "小时", 0, 40, 0.5, 0),
      p("rate", "每日新增睡眠债", "小时", -3, 6, 0.25, 2),
      p("duration", "观察天数", "天", 1, 30, 1, 7),
    ],
    metrics: [
      m("sleep-debt-total", "累计睡眠债", "finalValue", "number", "小时"),
      m("sleep-debt-change", "期间变化", "totalChange", "number", "小时"),
    ],
    chart: chart("area", ["area", "line", "bar"], "天", "睡眠债 小时"),
    explanation: explanation(
      "累计睡眠债 = 已有睡眠债 + 每日新增睡眠债 × 天数",
      ["把每天少睡的时间直接累加", "负值代表每天补回一部分"],
      "睡眠需求和恢复机制因人而异，不用于健康诊断。",
    ),
    keywords: ["睡眠", "睡觉", "少睡", "熬夜", "睡眠债", "欠觉", "恢复"],
    source: "builtin",
  },
  {
    version: 1,
    id: "weight-trend",
    title: "体重趋势估算",
    category: "生活日常",
    question: "保持当前习惯，未来几周体重趋势会怎样？",
    modelType: "linear",
    parameters: [
      p("initial", "当前体重", "kg", 35, 200, 0.5, 70),
      p("rate", "每周变化", "kg", -2, 2, 0.1, -0.4),
      p("duration", "观察周数", "周", 1, 52, 1, 12),
    ],
    metrics: [
      m("weight-final", "期末体重", "finalValue", "number", "kg"),
      m("weight-change", "体重变化", "totalChange", "number", "kg"),
    ],
    chart: chart("line", ["line", "area", "bar"], "周", "体重 kg"),
    explanation: explanation(
      "期末体重 = 当前体重 + 每周变化 × 周数",
      ["把短期变化近似为直线", "未模拟代谢适应、水分和肌肉变化"],
      "真实体重不会长期线性变化，不用于医疗或减重方案。",
    ),
    keywords: ["体重", "减重", "减肥", "大卡", "热量", "每周", "公斤"],
    source: "builtin",
  },
  {
    version: 1,
    id: "learning-progress",
    title: "学习进度累积",
    category: "生活日常",
    question: "每天完成固定学习量，一个月能推进多少？",
    modelType: "linear",
    parameters: [
      p("initial", "已经完成", "页", 0, 5000, 10, 0),
      p("rate", "每日完成", "页", 1, 300, 1, 20),
      p("duration", "持续天数", "天", 1, 365, 1, 30),
    ],
    metrics: [
      m("learning-final", "累计完成", "finalValue", "number", "页"),
      m("learning-change", "期间新增", "totalChange", "number", "页"),
    ],
    chart: chart("bar", ["bar", "area", "line"], "天", "累计页数"),
    explanation: explanation(
      "累计完成量 = 已完成量 + 每日完成量 × 天数",
      ["每日学习量保持一致", "未考虑休息日和难度变化"],
      "适合制定节奏，不代表掌握程度。",
    ),
    keywords: ["学习", "阅读", "读书", "每天", "页", "进度", "读完"],
    source: "builtin",
  },
  {
    version: 1,
    id: "phone-battery",
    title: "手机电量续航",
    category: "生活日常",
    question: "边充电边使用时，手机电量还能维持多久？",
    modelType: "inventory",
    parameters: [
      p("initialStock", "当前电量", "%", 0, 100, 1, 82),
      p("dailyInflow", "每小时充电", "%", 0, 60, 1, 0),
      p("dailyOutflow", "每小时耗电", "%", 1, 60, 1, 12),
      p("duration", "观察时长", "小时", 1, 24, 1, 10),
    ],
    metrics: [
      m("battery-final", "期末电量", "finalValue", "percent"),
      m("battery-life", "预计续航", "depletionTime", "duration", "小时"),
      m("battery-net", "每小时净变化", "netDailyChange", "number", "%"),
    ],
    chart: chart("step", ["step", "area", "line", "bar"], "小时", "电量 %"),
    explanation: explanation(
      "电量 = 当前电量 + 充电速度 × 时间 − 耗电速度 × 时间，最低为零",
      ["充电和耗电速度保持稳定", "忽略电池温度与低电量保护"],
      "用于比较使用强度，不代表真实电池检测结果。",
    ),
    keywords: ["手机", "电量", "电池", "续航", "充电", "刷视频", "耗电"],
    source: "builtin",
  },

  // 自然科学
  {
    version: 1,
    id: "plant-growth",
    title: "植物生长上限",
    category: "自然科学",
    question: "一株植物会怎样从幼苗逐渐接近最大高度？",
    modelType: "logistic",
    parameters: [
      p("initial", "当前高度", "cm", 1, 200, 1, 8),
      p("capacity", "环境高度上限", "cm", 10, 500, 5, 120),
      p("growthRate", "每日增长强度", "%", 1, 80, 1, 18),
      p("duration", "观察天数", "天", 1, 120, 1, 45),
    ],
    metrics: [
      m("plant-final", "期末高度", "finalValue", "number", "cm"),
      m("plant-capacity", "接近上限", "capacityPercent", "percent"),
    ],
    chart: chart("line", ["line", "area", "bar"], "天", "高度 cm"),
    explanation: explanation(
      "高度 = 上限 ÷ (1 + 初始差距 × e^(-增长率 × 时间))",
      ["环境承载上限固定", "增长率用于比较情景"],
      "用于理解 S 型成长，不替代真实栽培记录。",
    ),
    keywords: ["植物", "幼苗", "生长", "高度", "盆栽", "上限", "长大"],
    source: "builtin",
    featured: true,
  },
  {
    version: 1,
    id: "bacteria-growth",
    title: "培养皿菌落扩张",
    category: "自然科学",
    question: "有限空间里的菌落会怎样先快速扩张再趋缓？",
    modelType: "logistic",
    parameters: [
      p("initial", "初始菌落", "个", 1, 10000, 10, 100),
      p("capacity", "培养皿上限", "个", 1000, 1000000, 1000, 100000),
      p("growthRate", "每小时增长强度", "%", 1, 100, 1, 45),
      p("duration", "观察小时", "小时", 1, 48, 1, 20),
    ],
    metrics: [
      m("bacteria-final", "期末菌落", "finalValue", "number", "个"),
      m("bacteria-capacity", "空间占比", "capacityPercent", "percent"),
    ],
    chart: chart("area", ["area", "line", "bar"], "小时", "菌落数量"),
    explanation: explanation(
      "菌落数按 S 型曲线接近培养皿承载上限",
      ["营养和空间上限保持固定", "增长强度为简化参数"],
      "仅用于数学科普情景，不用于实验室安全操作。",
    ),
    keywords: ["细菌", "菌落", "培养皿", "繁殖", "扩张", "铺满", "微生物"],
    source: "builtin",
  },
  {
    version: 1,
    id: "radioactive-decay",
    title: "放射性物质衰减",
    category: "自然科学",
    question: "经过若干个半衰期后，样本理论上还剩多少？",
    modelType: "decay",
    parameters: [
      p("initial", "初始质量", "g", 1, 10000, 1, 1000),
      p("halfLife", "半衰期", "年", 0.1, 10000, 0.1, 30),
      p("duration", "经过时间", "年", 1, 10000, 1, 120),
    ],
    metrics: [
      m("isotope-final", "理论剩余", "finalValue", "number", "g"),
      m("isotope-percent", "剩余比例", "percentRemaining", "percent"),
    ],
    chart: chart("line", ["line", "area", "step"], "年", "理论质量 g"),
    explanation: explanation(
      "剩余质量 = 初始质量 × 0.5^(经过时间 ÷ 半衰期)",
      ["半衰期保持不变", "只描述统计期望"],
      "仅用于理解衰减数学，不用于材料处置或安全操作。",
    ),
    keywords: ["放射性", "同位素", "半衰期", "衰变", "物质", "样本", "剩余"],
    source: "builtin",
  },
  {
    version: 1,
    id: "rainwater-tank",
    title: "雨水储水箱变化",
    category: "自然科学",
    question: "每天收集雨水并用水，储水箱会剩多少？",
    modelType: "inventory",
    parameters: [
      p("initialStock", "当前储水", "L", 0, 100000, 100, 5000),
      p("dailyInflow", "每日集雨", "L", 0, 10000, 50, 600),
      p("dailyOutflow", "每日用水", "L", 0, 10000, 50, 450),
      p("duration", "观察天数", "天", 1, 365, 1, 30),
    ],
    metrics: [
      m("water-final", "期末储水", "finalValue", "number", "L"),
      m("water-depletion", "预计用尽", "depletionTime", "duration", "天"),
      m("water-net", "每日净变化", "netDailyChange", "number", "L"),
    ],
    chart: chart("area", ["area", "line", "step", "bar"], "天", "储水 L"),
    explanation: explanation(
      "每日储水 = 上日储水 + 集雨 − 用水，最低为零",
      ["每日雨量和用水量保持不变", "未设置水箱容量上限"],
      "用于观察收支平衡，不代表真实天气预测。",
    ),
    keywords: ["雨水", "储水", "水箱", "集雨", "用水", "下雨", "水量"],
    source: "builtin",
  },
  {
    version: 1,
    id: "food-chain",
    title: "生态食物链留存",
    category: "自然科学",
    question: "能量经过生产者、草食者和捕食者后还剩多少？",
    modelType: "funnel",
    parameters: [
      p("audience", "初始能量", "kJ", 100, 10000000, 100, 100000),
      p("rate1", "生产者留存", "%", 1, 100, 1, 30),
      p("rate2", "草食层传递", "%", 1, 100, 1, 12),
      p("rate3", "捕食层传递", "%", 1, 100, 1, 10),
    ],
    metrics: [
      m("food-final", "顶层能量", "finalValue", "number", "kJ"),
      m("food-rate", "整体留存", "overallRate", "percent"),
    ],
    chart: chart("funnel", ["funnel", "bar"], "营养层", "能量 kJ"),
    explanation: explanation(
      "下一营养层能量 = 上一层能量 × 当前传递率",
      ["每层使用固定平均传递率", "未模拟物种数量变化"],
      "用于理解能量传递，不代表具体生态系统测量。",
    ),
    keywords: ["生态", "食物链", "能量", "营养层", "草食", "捕食", "留存"],
    source: "builtin",
    stageLabels: ["太阳输入", "生产者", "草食者", "捕食者"],
  },

  // 游戏世界
  {
    version: 1,
    id: "game-payback",
    title: "小游戏买量回本",
    category: "游戏世界",
    question: "小游戏每天买量 5000 元，多久能够回本？",
    modelType: "payback",
    parameters: [
      p("dailySpend", "每日买量成本", "元", 500, 50000, 500, 5000),
      p("dailyUsers", "每日新增用户", "人", 100, 20000, 100, 4000),
      p("day1Retention", "有效活跃比例", "%", 5, 100, 1, 35),
      p("revenuePerActiveUser", "活跃用户日收益", "元", 0.1, 10, 0.1, 1.2),
      p("duration", "观察天数", "天", 7, 90, 1, 30),
    ],
    metrics: [
      m("payback-day", "预计回本日", "paybackDay", "duration", "天"),
      m("profit", "期末净收益", "finalValue", "currency", "元"),
      m("roi", "观察期 ROI", "roi", "percent"),
    ],
    chart: chart("area", ["area", "line", "bar"], "天", "累计金额 元", ["revenue", "cost"]),
    explanation: explanation(
      "累计净收益 = 累计活跃收益 − 累计买量成本",
      ["每日投放规模保持不变", "历史用户按同一有效活跃比例递减", "未计入自然量及其他运营成本"],
      "用于比较投放参数，不代表真实经营结果。",
    ),
    keywords: ["小游戏", "买量", "投放", "回本", "广告", "roi", "新增用户"],
    source: "builtin",
    featured: true,
  },
  {
    version: 1,
    id: "game-progression",
    title: "游戏数值成长曲线",
    category: "游戏世界",
    question: "按当前经验获取速度，玩家多久能达到目标进度？",
    modelType: "linear",
    parameters: [
      p("initial", "当前累计经验", "XP", 0, 1000000, 100, 5000),
      p("rate", "每日获取经验", "XP", 100, 100000, 100, 2500),
      p("duration", "观察天数", "天", 1, 365, 1, 30),
    ],
    metrics: [
      m("progression-final", "期末累计经验", "finalValue", "number", "XP"),
      m("progression-gain", "期间获得经验", "totalChange", "number", "XP"),
    ],
    chart: chart("bar", ["bar", "area", "line"], "天", "累计经验 XP"),
    explanation: explanation(
      "累计经验 = 当前经验 + 每日经验获取 × 天数",
      ["每日经验获取速度不变", "未包含等级提高后的经验需求变化"],
      "用于快速观察成长节奏，不是完整数值平衡器。",
    ),
    keywords: ["游戏", "角色", "升级", "经验", "成长", "满级", "数值曲线"],
    source: "builtin",
  },
  {
    version: 1,
    id: "stamina-recovery",
    title: "游戏体力恢复",
    category: "游戏世界",
    question: "自然恢复与消耗同时发生时，体力还剩多少？",
    modelType: "inventory",
    parameters: [
      p("initialStock", "当前体力", "点", 0, 500, 1, 30),
      p("dailyInflow", "每小时恢复", "点", 0, 60, 1, 10),
      p("dailyOutflow", "每小时消耗", "点", 0, 100, 1, 4),
      p("duration", "观察小时", "小时", 1, 48, 1, 12),
    ],
    metrics: [
      m("stamina-final", "期末体力", "finalValue", "number", "点"),
      m("stamina-empty", "预计耗尽", "depletionTime", "duration", "小时"),
      m("stamina-net", "每小时净变化", "netDailyChange", "number", "点"),
    ],
    chart: chart("step", ["step", "area", "line", "bar"], "小时", "体力 点"),
    explanation: explanation(
      "体力 = 当前体力 + 恢复 − 消耗，最低为零",
      ["恢复和消耗速度连续且稳定", "未设置体力上限"],
      "用于体验资源节奏，不代表具体游戏规则。",
    ),
    keywords: ["游戏", "体力", "恢复", "自然回复", "刷本", "消耗", "回满"],
    source: "builtin",
  },
  {
    version: 1,
    id: "gacha-pity",
    title: "抽卡保底进度",
    category: "游戏世界",
    question: "在给定单抽概率与保底次数下，累计命中概率怎样变化？",
    modelType: "probability",
    parameters: [
      p("chance", "单次命中概率", "%", 0.1, 20, 0.1, 1.6),
      p("attempts", "当前抽数", "抽", 1, 300, 1, 60),
      p("guaranteeAt", "硬保底次数", "抽", 0, 300, 1, 90),
    ],
    metrics: [
      m("gacha-probability", "累计命中概率", "finalValue", "percent"),
      m("gacha-trials", "有效尝试", "effectiveTrials", "number", "次"),
      m("gacha-median", "概率过半约需", "medianAttempt", "duration", "抽"),
    ],
    chart: chart("step", ["step", "line", "area", "bar"], "抽数", "累计概率 %"),
    explanation: explanation(
      "累计概率 = 1 − (1 − 单次概率)^抽数；达到硬保底时记为 100%",
      ["每次普通抽取相互独立", "硬保底只按设定次数处理"],
      "仅用于理解概率，不承诺真实游戏结果或实际掉落。",
    ),
    keywords: ["抽卡", "保底", "概率", "卡池", "欧非", "多少抽", "命中"],
    source: "builtin",
  },
  {
    version: 1,
    id: "level-funnel",
    title: "关卡通关漏斗",
    category: "游戏世界",
    question: "玩家从进入关卡到最终通关会在哪一步流失？",
    modelType: "funnel",
    parameters: [
      p("audience", "进入玩家", "人", 100, 1000000, 100, 20000),
      p("rate1", "到达中段", "%", 1, 100, 1, 72),
      p("rate2", "到达首领", "%", 1, 100, 1, 58),
      p("rate3", "最终通关", "%", 1, 100, 1, 45),
    ],
    metrics: [
      m("level-final", "通关玩家", "finalValue", "number", "人"),
      m("level-rate", "整体通关率", "overallRate", "percent"),
    ],
    chart: chart("funnel", ["funnel", "bar"], "阶段", "玩家数"),
    explanation: explanation(
      "下一阶段玩家 = 上一阶段玩家 × 当前通过率",
      ["每段通过率稳定", "不考虑重复挑战"],
      "用于观察关卡流失，不代表真实玩家行为预测。",
    ),
    keywords: ["游戏", "关卡", "通关", "玩家", "首领", "boss", "流失", "漏斗"],
    source: "builtin",
    stageLabels: ["进入", "中段", "首领", "通关"],
  },

  // 商业决策
  {
    version: 1,
    id: "compound-savings",
    title: "定期存钱与复利",
    category: "商业决策",
    question: "每月固定存钱，十年后本金和收益会变成多少？",
    modelType: "compound",
    parameters: [
      p("principal", "初始本金", "元", 0, 1000000, 1000, 10000),
      p("contribution", "每月投入", "元", 100, 50000, 100, 3000),
      p("annualRate", "假设年化收益", "%", -10, 20, 0.5, 4),
      p("years", "持续年限", "年", 1, 40, 1, 10),
    ],
    metrics: [
      m("balance", "期末金额", "finalValue", "currency", "元"),
      m("contributed", "累计投入", "totalContributed", "currency", "元"),
      m("interest", "估算收益", "interestEarned", "currency", "元"),
    ],
    chart: chart("area", ["area", "line", "bar"], "月", "累计金额 元"),
    explanation: explanation(
      "每月余额 = 上月余额 × (1 + 年化收益率 ÷ 12) + 每月投入",
      ["按月复利", "每月月底投入", "收益率在整个周期内保持不变"],
      "仅用于教育性质的情景估算，不代表实际投资结果。",
    ),
    keywords: ["存钱", "复利", "本金", "每月", "年化", "收益", "十年", "投资"],
    source: "builtin",
  },
  {
    version: 1,
    id: "sales-funnel",
    title: "销售漏斗转化",
    category: "商业决策",
    question: "从访客到线索再到成交，最终会留下多少客户？",
    modelType: "funnel",
    parameters: [
      p("audience", "初始访客", "人", 100, 1000000, 100, 10000),
      p("rate1", "线索转化率", "%", 1, 100, 1, 20),
      p("rate2", "有效沟通率", "%", 1, 100, 1, 35),
      p("rate3", "成交率", "%", 1, 100, 1, 15),
    ],
    metrics: [
      m("sales-final", "预计成交", "finalValue", "number", "人"),
      m("sales-rate", "整体转化率", "overallRate", "percent"),
    ],
    chart: chart("funnel", ["funnel", "bar"], "阶段", "人数"),
    explanation: explanation(
      "下一阶段人数 = 上一阶段人数 × 当前阶段转化率",
      ["各阶段转化率独立且稳定", "未考虑重复线索和跨期成交"],
      "用于定位漏斗瓶颈，不代表实际销售承诺。",
    ),
    keywords: ["销售", "漏斗", "访客", "线索", "成交", "客户", "转化"],
    source: "builtin",
    stageLabels: ["访客", "线索", "沟通", "成交"],
  },
  {
    version: 1,
    id: "subscription-growth",
    title: "订阅用户增长",
    category: "商业决策",
    question: "每月新增与流失相抵后，订阅用户会增长到多少？",
    modelType: "linear",
    parameters: [
      p("initial", "当前订阅用户", "人", 0, 1000000, 100, 10000),
      p("rate", "每月净增用户", "人", -50000, 100000, 100, 1200),
      p("duration", "观察月数", "月", 1, 60, 1, 12),
    ],
    metrics: [
      m("subscriber-final", "期末订阅用户", "finalValue", "number", "人"),
      m("subscriber-change", "累计净变化", "totalChange", "number", "人"),
    ],
    chart: chart("line", ["line", "area", "bar"], "月", "订阅用户"),
    explanation: explanation(
      "期末用户 = 当前用户 + 每月净增用户 × 月数",
      ["净增已经包含新增和流失", "增长速度在观察期保持不变"],
      "适合快速做情景比较，不是完整订阅预测模型。",
    ),
    keywords: ["订阅", "用户", "每月", "增长", "新增", "流失", "留存"],
    source: "builtin",
  },
  {
    version: 1,
    id: "inventory-runway",
    title: "库存还能撑多久",
    category: "商业决策",
    question: "按现在的销量和补货速度，库存什么时候耗尽？",
    modelType: "inventory",
    parameters: [
      p("initialStock", "当前库存", "件", 0, 1000000, 100, 10000),
      p("dailyInflow", "每日补货", "件", 0, 100000, 50, 200),
      p("dailyOutflow", "每日销量", "件", 0, 100000, 50, 700),
      p("duration", "观察天数", "天", 1, 365, 1, 30),
    ],
    metrics: [
      m("inventory-final", "期末库存", "finalValue", "number", "件"),
      m("inventory-days", "预计耗尽时间", "depletionTime", "duration", "天"),
      m("inventory-net", "每日净变化", "netDailyChange", "number", "件"),
    ],
    chart: chart("step", ["step", "area", "line", "bar"], "天", "库存 件"),
    explanation: explanation(
      "每日库存 = 上日库存 + 每日补货 − 每日销量，最低为零",
      ["补货和销量每天保持不变", "不考虑安全库存和交期波动"],
      "用于快速估算库存窗口，正式采购需结合实时数据。",
    ),
    keywords: ["库存", "仓库", "销量", "补货", "耗尽", "缺货", "还能撑"],
    source: "builtin",
  },
  {
    version: 1,
    id: "budget-burn",
    title: "项目预算燃尽",
    category: "商业决策",
    question: "按当前花费速度，项目预算还能支撑多少天？",
    modelType: "inventory",
    parameters: [
      p("initialStock", "剩余预算", "元", 0, 10000000, 1000, 500000),
      p("dailyInflow", "每日新增预算", "元", 0, 100000, 500, 0),
      p("dailyOutflow", "每日花费", "元", 100, 500000, 500, 15000),
      p("duration", "观察天数", "天", 1, 365, 1, 60),
    ],
    metrics: [
      m("budget-final", "期末余额", "finalValue", "currency", "元"),
      m("budget-days", "预计可支撑", "depletionTime", "duration", "天"),
      m("budget-net", "每日净变化", "netDailyChange", "currency", "元"),
    ],
    chart: chart("area", ["area", "step", "line", "bar"], "天", "预算 元"),
    explanation: explanation(
      "每日余额 = 上日余额 + 新增预算 − 每日花费，最低为零",
      ["每日花费保持不变", "未包含一次性大额支出"],
      "用于观察预算燃尽速度，不替代财务预算。",
    ),
    keywords: ["项目", "预算", "花费", "燃尽", "成本", "资金", "能撑多久"],
    source: "builtin",
  },

  // 社交传播
  {
    version: 1,
    id: "event-attendance",
    title: "活动到场漏斗",
    category: "社交传播",
    question: "从曝光、报名到最终到场，活动能来多少人？",
    modelType: "funnel",
    parameters: [
      p("audience", "活动曝光", "人", 100, 1000000, 100, 20000),
      p("rate1", "报名转化率", "%", 1, 100, 1, 8),
      p("rate2", "报名到场率", "%", 1, 100, 1, 65),
    ],
    metrics: [
      m("attendance-final", "预计到场", "finalValue", "number", "人"),
      m("attendance-rate", "整体到场率", "overallRate", "percent"),
    ],
    chart: chart("funnel", ["funnel", "bar"], "阶段", "人数"),
    explanation: explanation(
      "预计到场 = 活动曝光 × 报名转化率 × 报名到场率",
      ["报名和到场比例保持稳定", "未考虑重复曝光和临时扩容"],
      "用于活动规模预估，实际到场受渠道和天气等因素影响。",
    ),
    keywords: ["活动", "报名", "到场", "曝光", "参会", "人数", "转化"],
    source: "builtin",
    stageLabels: ["曝光", "报名", "到场"],
  },
  {
    version: 1,
    id: "short-video-decay",
    title: "短视频热度衰减",
    category: "社交传播",
    question: "一条短视频的热度经过几天会衰减到多少？",
    modelType: "decay",
    parameters: [
      p("initial", "初始热度", "点", 100, 10000000, 100, 100000),
      p("halfLife", "热度半衰期", "天", 0.5, 30, 0.5, 3),
      p("duration", "观察天数", "天", 1, 60, 1, 14),
    ],
    metrics: [
      m("video-final", "期末热度", "finalValue", "number", "点"),
      m("video-percent", "剩余热度", "percentRemaining", "percent"),
    ],
    chart: chart("area", ["area", "line", "step", "bar"], "天", "热度 点"),
    explanation: explanation(
      "剩余热度 = 初始热度 × 0.5^(经过天数 ÷ 热度半衰期)",
      ["自然热度按固定半衰期下降", "未加入二次传播或平台推荐"],
      "用于比较内容生命周期，不预测真实播放量。",
    ),
    keywords: ["短视频", "视频", "热度", "播放", "衰减", "流量", "推荐"],
    source: "builtin",
  },
  {
    version: 1,
    id: "livestream-retention",
    title: "直播观看留存",
    category: "社交传播",
    question: "观众从进入直播间到互动和看完会留下多少？",
    modelType: "funnel",
    parameters: [
      p("audience", "进入直播间", "人", 100, 10000000, 100, 50000),
      p("rate1", "停留一分钟", "%", 1, 100, 1, 55),
      p("rate2", "参与互动", "%", 1, 100, 1, 32),
      p("rate3", "留到结束", "%", 1, 100, 1, 25),
    ],
    metrics: [
      m("live-final", "留到结束", "finalValue", "number", "人"),
      m("live-rate", "整体留存率", "overallRate", "percent"),
    ],
    chart: chart("funnel", ["funnel", "bar"], "阶段", "观众数"),
    explanation: explanation(
      "下一阶段观众 = 上一阶段观众 × 当前留存率",
      ["阶段留存率保持稳定", "未考虑中途新进入观众"],
      "用于观察直播漏斗，不代表实际流量承诺。",
    ),
    keywords: ["直播", "观众", "观看", "留存", "互动", "看完", "直播间"],
    source: "builtin",
    stageLabels: ["进入", "停留", "互动", "结束"],
  },
  {
    version: 1,
    id: "community-growth",
    title: "社区成员增长",
    category: "社交传播",
    question: "社区成员增长到一定规模后会怎样趋缓？",
    modelType: "logistic",
    parameters: [
      p("initial", "当前成员", "人", 1, 1000000, 100, 3000),
      p("capacity", "社区容量", "人", 1000, 10000000, 1000, 100000),
      p("growthRate", "每月增长强度", "%", 1, 80, 1, 20),
      p("duration", "观察月数", "月", 1, 60, 1, 24),
    ],
    metrics: [
      m("community-final", "期末成员", "finalValue", "number", "人"),
      m("community-capacity", "容量占比", "capacityPercent", "percent"),
    ],
    chart: chart("line", ["line", "area", "bar"], "月", "社区成员"),
    explanation: explanation(
      "成员数按 S 型曲线逐渐接近社区容量",
      ["增长强度和容量保持固定", "未拆分新增与流失来源"],
      "用于比较增长阶段，不代表真实社群规模预测。",
    ),
    keywords: ["社区", "社群", "成员", "增长", "容量", "用户", "趋缓"],
    source: "builtin",
  },
  {
    version: 1,
    id: "message-spread",
    title: "消息扩散上限",
    category: "社交传播",
    question: "一条消息在有限人群中会怎样扩散并趋于饱和？",
    modelType: "logistic",
    parameters: [
      p("initial", "最初知晓人数", "人", 1, 1000000, 10, 100),
      p("capacity", "可触达人群", "人", 1000, 100000000, 1000, 500000),
      p("growthRate", "每小时扩散强度", "%", 1, 100, 1, 35),
      p("duration", "观察小时", "小时", 1, 72, 1, 24),
    ],
    metrics: [
      m("message-final", "期末知晓", "finalValue", "number", "人"),
      m("message-capacity", "触达占比", "capacityPercent", "percent"),
    ],
    chart: chart("area", ["area", "line", "bar"], "小时", "知晓人数"),
    explanation: explanation(
      "知晓人数按 S 型曲线接近可触达人群上限",
      ["人群上限固定", "扩散强度不随内容变化"],
      "用于理解饱和传播，不预测真实舆情或平台流量。",
    ),
    keywords: ["消息", "扩散", "传播", "转发", "触达", "知晓", "裂变"],
    source: "builtin",
  },

  // 趣味脑洞
  {
    version: 1,
    id: "restaurant-queue",
    title: "餐厅排队消化",
    category: "趣味脑洞",
    question: "客人不断到达时，餐厅多久能消化当前排队？",
    modelType: "queue",
    parameters: [
      p("initialQueue", "当前排队", "桌", 0, 1000, 1, 36),
      p("arrivalRate", "每小时新到", "桌", 0, 200, 1, 18),
      p("serviceRate", "每小时入座", "桌", 0, 200, 1, 26),
      p("duration", "观察小时", "小时", 1, 24, 1, 8),
    ],
    metrics: [
      m("restaurant-final", "期末排队", "finalValue", "number", "桌"),
      m("restaurant-clear", "预计清空", "clearTime", "duration", "小时"),
      m("restaurant-net", "每小时净变化", "netRate", "number", "桌"),
    ],
    chart: chart("step", ["step", "line", "area", "bar"], "小时", "排队桌数"),
    explanation: explanation(
      "排队数 = 当前排队 + 新到速度 × 时间 − 入座速度 × 时间，最低为零",
      ["到达和入座速度稳定", "未考虑拼桌和预约"],
      "用于体验队列收支，不代表真实等位时间。",
    ),
    keywords: ["餐厅", "排队", "等位", "入座", "客人", "多久", "消化"],
    source: "builtin",
  },
  {
    version: 1,
    id: "birthday-collision",
    title: "生日碰撞概率",
    category: "趣味脑洞",
    question: "一个房间里有多少人时，两人同生日的概率会超过一半？",
    modelType: "probability",
    attemptTransform: "pairwise",
    parameters: [
      p("chance", "任意一对同生日", "%", 0.1, 1, 0.01, 100 / 365),
      p("attempts", "房间人数", "人", 2, 100, 1, 23),
      p("guaranteeAt", "数学保底", "人", 0, 400, 1, 0),
    ],
    metrics: [
      m("birthday-probability", "至少一对同生日", "finalValue", "percent"),
      m("birthday-pairs", "配对数量", "effectiveTrials", "number", "对"),
    ],
    chart: chart("area", ["area", "line", "step", "bar"], "人数", "概率 %"),
    explanation: explanation(
      "近似概率 = 1 − (1 − 1/365)^(人数 × (人数 − 1) ÷ 2)",
      ["忽略闰日", "生日在一年中近似均匀分布", "使用独立配对近似"],
      "用于直观体验组合数量增长，结果是简化数学估算。",
    ),
    keywords: ["生日", "相同生日", "碰撞", "概率", "房间", "多少人", "过半"],
    source: "builtin",
  },
  {
    version: 1,
    id: "mars-colony",
    title: "火星殖民增长",
    category: "趣味脑洞",
    question: "受基地容量限制时，火星殖民人口会怎样增长？",
    modelType: "logistic",
    parameters: [
      p("initial", "首批居民", "人", 1, 100000, 10, 120),
      p("capacity", "基地容量", "人", 1000, 10000000, 1000, 100000),
      p("growthRate", "每年增长强度", "%", 1, 80, 1, 16),
      p("duration", "观察年数", "年", 1, 100, 1, 50),
    ],
    metrics: [
      m("mars-final", "期末居民", "finalValue", "number", "人"),
      m("mars-capacity", "基地占用", "capacityPercent", "percent"),
    ],
    chart: chart("line", ["line", "area", "bar"], "年", "居民人数"),
    explanation: explanation(
      "居民数按 S 型曲线接近基地容量",
      ["基地容量固定", "增长强度包含迁入与自然变化的简化合计"],
      "纯属科幻数学情景，不是航天人口预测。",
    ),
    keywords: ["火星", "殖民", "太空", "基地", "人口", "增长", "外星"],
    source: "builtin",
  },
  {
    version: 1,
    id: "pizza-consumption",
    title: "派对披萨消耗",
    category: "趣味脑洞",
    question: "派对中披萨送达和被吃掉同时发生，多久会吃完？",
    modelType: "inventory",
    parameters: [
      p("initialStock", "现有披萨", "片", 0, 1000, 1, 80),
      p("dailyInflow", "每小时送达", "片", 0, 200, 1, 12),
      p("dailyOutflow", "每小时吃掉", "片", 0, 300, 1, 28),
      p("duration", "派对时长", "小时", 1, 24, 1, 8),
    ],
    metrics: [
      m("pizza-final", "期末披萨", "finalValue", "number", "片"),
      m("pizza-empty", "预计吃完", "depletionTime", "duration", "小时"),
      m("pizza-net", "每小时净变化", "netDailyChange", "number", "片"),
    ],
    chart: chart("step", ["step", "area", "line", "bar"], "小时", "披萨 片"),
    explanation: explanation(
      "披萨片数 = 当前数量 + 送达 − 吃掉，最低为零",
      ["送达和食用速度保持稳定", "未考虑口味差异"],
      "用于派对脑洞估算，不代表营养或健康建议。",
    ),
    keywords: ["披萨", "派对", "吃完", "消耗", "送达", "聚会", "食物"],
    source: "builtin",
  },
  {
    version: 1,
    id: "theme-park-queue",
    title: "游乐园排队变化",
    category: "趣味脑洞",
    question: "游客到达速度超过项目接待速度时，队伍会变多长？",
    modelType: "queue",
    parameters: [
      p("initialQueue", "当前排队", "人", 0, 10000, 10, 180),
      p("arrivalRate", "每小时到达", "人", 0, 5000, 10, 420),
      p("serviceRate", "每小时接待", "人", 0, 5000, 10, 360),
      p("duration", "观察小时", "小时", 1, 16, 1, 6),
    ],
    metrics: [
      m("park-final", "期末排队", "finalValue", "number", "人"),
      m("park-clear", "预计清空", "clearTime", "duration", "小时"),
      m("park-net", "每小时净变化", "netRate", "number", "人"),
    ],
    chart: chart("step", ["step", "line", "area", "bar"], "小时", "排队人数"),
    explanation: explanation(
      "排队人数 = 当前排队 + 到达速度 × 时间 − 接待速度 × 时间，最低为零",
      ["到达和接待速度保持稳定", "未考虑临时停机和预约通道"],
      "用于理解排队变化，不代表真实景区等候时间。",
    ),
    keywords: ["游乐园", "景区", "项目", "排队", "队伍", "游客", "接待"],
    source: "builtin",
  },
];

export const EXPERIMENTS = Object.freeze(library.map(item => Object.freeze(item)));

export function getExperiment(id) {
  const experiment = EXPERIMENTS.find(item => item.id === id);
  return experiment ? structuredClone(experiment) : null;
}
