const DISCLAIMER = "互动估算，不构成专业建议。";

const p = (id, label, unit, min, max, step, defaultValue) => ({
  id,
  label,
  unit,
  min,
  max,
  step,
  default: defaultValue,
});

const m = (id, label, output, format = "number", unit = "") => ({
  id,
  label,
  output,
  format,
  unit,
});

const explanation = (formula, assumptions, boundary) => ({
  formula,
  assumptions,
  boundary,
  disclaimer: DISCLAIMER,
});

const library = [
  {
    version: 1,
    id: "caffeine-decay",
    title: "咖啡因还剩多少？",
    category: "生活科普",
    question: "下午喝咖啡，晚上体内还剩多少咖啡因？",
    modelType: "decay",
    parameters: [
      p("initial", "摄入量", "mg", 20, 500, 10, 200),
      p("halfLife", "半衰期", "小时", 2, 10, 0.5, 5),
      p("duration", "观察时长", "小时", 4, 24, 1, 12),
    ],
    metrics: [
      m("remaining", "最终剩余", "finalValue", "number", "mg"),
      m("remaining-percent", "剩余比例", "percentRemaining", "percent"),
    ],
    chart: { type: "area", xLabel: "小时", yLabel: "咖啡因 mg", series: ["value"] },
    explanation: explanation(
      "剩余量 = 初始摄入量 × 0.5^(经过时间 ÷ 半衰期)",
      ["按固定半衰期估算", "个体代谢速度可能明显不同"],
      "仅用于理解指数衰减，不用于医疗判断。",
    ),
    keywords: ["咖啡", "咖啡因", "半衰期", "代谢", "晚上", "摄入"],
    source: "builtin",
    featured: true,
  },
  {
    version: 1,
    id: "game-payback",
    title: "小游戏买量回本",
    category: "游戏产品",
    question: "小游戏每天买量 5000 元，多久能够回本？",
    modelType: "payback",
    parameters: [
      p("dailySpend", "每日买量成本", "元", 500, 50000, 500, 5000),
      p("dailyUsers", "每日新增用户", "人", 100, 20000, 100, 4000),
      p("day1Retention", "有效活跃比例", "%", 5, 100, 1, 35),
      p("revenuePerActiveUser", "活跃用户日收益", "元", 0.1, 10, 0.1, 1.2),
      p("duration", "观察天数", "天", 7, 90, 1, 30),
    ],
    metrics: [
      m("payback-day", "预计回本日", "paybackDay", "duration", "天"),
      m("profit", "期末净收益", "finalValue", "currency", "元"),
      m("roi", "观察期 ROI", "roi", "percent"),
    ],
    chart: { type: "area", xLabel: "天", yLabel: "累计金额 元", series: ["revenue", "cost"] },
    explanation: explanation(
      "每日净收益 = 新增用户 × 有效活跃比例 × 活跃用户日收益 − 每日买量成本",
      ["每日投放规模保持不变", "收益和有效活跃比例按固定值估算", "未计入自然量及其他运营成本"],
      "用于比较投放参数，不代表真实经营结果。",
    ),
    keywords: ["小游戏", "买量", "投放", "回本", "广告", "roi", "新增用户"],
    source: "builtin",
    featured: true,
  },
  {
    version: 1,
    id: "compound-savings",
    title: "定期存钱与复利",
    category: "商业决策",
    question: "每月固定存钱，十年后本金和收益会变成多少？",
    modelType: "compound",
    parameters: [
      p("principal", "初始本金", "元", 0, 1000000, 1000, 10000),
      p("contribution", "每月投入", "元", 100, 50000, 100, 3000),
      p("annualRate", "假设年化收益", "%", -10, 20, 0.5, 4),
      p("years", "持续年限", "年", 1, 40, 1, 10),
    ],
    metrics: [
      m("balance", "期末金额", "finalValue", "currency", "元"),
      m("contributed", "累计投入", "totalContributed", "currency", "元"),
      m("interest", "估算收益", "interestEarned", "currency", "元"),
    ],
    chart: { type: "area", xLabel: "月", yLabel: "累计金额 元", series: ["value"] },
    explanation: explanation(
      "每月余额 = 上月余额 × (1 + 年化收益率 ÷ 12) + 每月投入",
      ["按月复利", "每月月底投入", "收益率在整个周期内保持不变"],
      "市场收益并不稳定，本实验不构成投资建议。",
    ),
    keywords: ["存钱", "复利", "本金", "每月", "年化", "收益", "十年"],
    source: "builtin",
    featured: true,
  },
  {
    version: 1,
    id: "sleep-debt",
    title: "睡眠债累积",
    category: "生活科普",
    question: "每天少睡一点，一周会积累多少睡眠债？",
    modelType: "linear",
    parameters: [
      p("initial", "已有睡眠债", "小时", 0, 40, 0.5, 0),
      p("rate", "每日新增睡眠债", "小时", -3, 6, 0.25, 2),
      p("duration", "观察天数", "天", 1, 30, 1, 7),
    ],
    metrics: [
      m("sleep-debt-total", "累计睡眠债", "finalValue", "number", "小时"),
      m("sleep-debt-change", "期间变化", "totalChange", "number", "小时"),
    ],
    chart: { type: "area", xLabel: "天", yLabel: "睡眠债 小时", series: ["value"] },
    explanation: explanation(
      "累计睡眠债 = 已有睡眠债 + 每日新增睡眠债 × 天数",
      ["把每天少睡的时间直接累加", "负值代表每天补回一部分"],
      "睡眠需求和恢复机制因人而异，不用于健康诊断。",
    ),
    keywords: ["睡眠", "睡觉", "少睡", "熬夜", "睡眠债", "欠觉", "恢复"],
    source: "builtin",
  },
  {
    version: 1,
    id: "weight-trend",
    title: "体重趋势估算",
    category: "生活科普",
    question: "保持当前习惯，未来几周体重趋势会怎样？",
    modelType: "linear",
    parameters: [
      p("initial", "当前体重", "kg", 35, 200, 0.5, 70),
      p("rate", "每周变化", "kg", -2, 2, 0.1, -0.4),
      p("duration", "观察周数", "周", 1, 52, 1, 12),
    ],
    metrics: [
      m("weight-final", "期末体重", "finalValue", "number", "kg"),
      m("weight-change", "体重变化", "totalChange", "number", "kg"),
    ],
    chart: { type: "line", xLabel: "周", yLabel: "体重 kg", series: ["value"] },
    explanation: explanation(
      "期末体重 = 当前体重 + 每周变化 × 周数",
      ["把短期变化近似为直线", "未模拟代谢适应、水分和肌肉变化"],
      "真实体重不会长期线性变化，不用于医疗或减重方案。",
    ),
    keywords: ["体重", "减重", "减肥", "大卡", "热量", "每周", "公斤"],
    source: "builtin",
  },
  {
    version: 1,
    id: "learning-progress",
    title: "学习进度累积",
    category: "生活科普",
    question: "每天完成固定学习量，一个月能推进多少？",
    modelType: "linear",
    parameters: [
      p("initial", "已经完成", "页", 0, 5000, 10, 0),
      p("rate", "每日完成", "页", 1, 300, 1, 20),
      p("duration", "持续天数", "天", 1, 365, 1, 30),
    ],
    metrics: [
      m("learning-final", "累计完成", "finalValue", "number", "页"),
      m("learning-change", "期间新增", "totalChange", "number", "页"),
    ],
    chart: { type: "area", xLabel: "天", yLabel: "累计页数", series: ["value"] },
    explanation: explanation(
      "累计完成量 = 已完成量 + 每日完成量 × 天数",
      ["每日学习量保持一致", "未考虑休息日和难度变化"],
      "适合制定节奏，不代表掌握程度。",
    ),
    keywords: ["学习", "阅读", "读书", "每天", "页", "进度", "读完"],
    source: "builtin",
  },
  {
    version: 1,
    id: "sales-funnel",
    title: "销售漏斗转化",
    category: "商业决策",
    question: "从访客到线索再到成交，最终会留下多少客户？",
    modelType: "funnel",
    parameters: [
      p("audience", "初始访客", "人", 100, 1000000, 100, 10000),
      p("rate1", "线索转化率", "%", 1, 100, 1, 20),
      p("rate2", "有效沟通率", "%", 1, 100, 1, 35),
      p("rate3", "成交率", "%", 1, 100, 1, 15),
    ],
    metrics: [
      m("sales-final", "预计成交", "finalValue", "number", "人"),
      m("sales-rate", "整体转化率", "overallRate", "percent"),
    ],
    chart: { type: "funnel", xLabel: "阶段", yLabel: "人数", series: ["value"] },
    explanation: explanation(
      "下一阶段人数 = 上一阶段人数 × 当前阶段转化率",
      ["各阶段转化率独立且稳定", "未考虑重复线索和跨期成交"],
      "用于定位漏斗瓶颈，不代表实际销售承诺。",
    ),
    keywords: ["销售", "漏斗", "访客", "线索", "成交", "客户", "转化"],
    source: "builtin",
    stageLabels: ["访客", "线索", "沟通", "成交"],
  },
  {
    version: 1,
    id: "subscription-growth",
    title: "订阅用户增长",
    category: "商业决策",
    question: "每月新增与流失相抵后，订阅用户会增长到多少？",
    modelType: "linear",
    parameters: [
      p("initial", "当前订阅用户", "人", 0, 1000000, 100, 10000),
      p("rate", "每月净增用户", "人", -50000, 100000, 100, 1200),
      p("duration", "观察月数", "月", 1, 60, 1, 12),
    ],
    metrics: [
      m("subscriber-final", "期末订阅用户", "finalValue", "number", "人"),
      m("subscriber-change", "累计净变化", "totalChange", "number", "人"),
    ],
    chart: { type: "area", xLabel: "月", yLabel: "订阅用户", series: ["value"] },
    explanation: explanation(
      "期末用户 = 当前用户 + 每月净增用户 × 月数",
      ["净增已经包含新增和流失", "增长速度在观察期保持不变"],
      "适合快速做情景比较，不是完整订阅预测模型。",
    ),
    keywords: ["订阅", "用户", "每月", "增长", "新增", "流失", "留存"],
    source: "builtin",
  },
  {
    version: 1,
    id: "inventory-runway",
    title: "库存还能撑多久",
    category: "商业决策",
    question: "按现在的销量和补货速度，库存什么时候耗尽？",
    modelType: "inventory",
    parameters: [
      p("initialStock", "当前库存", "件", 0, 1000000, 100, 10000),
      p("dailyInflow", "每日补货", "件", 0, 100000, 50, 200),
      p("dailyOutflow", "每日销量", "件", 0, 100000, 50, 700),
      p("duration", "观察天数", "天", 1, 365, 1, 30),
    ],
    metrics: [
      m("inventory-final", "期末库存", "finalValue", "number", "件"),
      m("inventory-days", "预计耗尽时间", "depletionTime", "duration", "天"),
      m("inventory-net", "每日净变化", "netDailyChange", "number", "件"),
    ],
    chart: { type: "area", xLabel: "天", yLabel: "库存 件", series: ["value"] },
    explanation: explanation(
      "每日库存 = 上日库存 + 每日补货 − 每日销量，最低为零",
      ["补货和销量每天保持不变", "不考虑安全库存和交期波动"],
      "用于快速估算库存窗口，正式采购需结合实时数据。",
    ),
    keywords: ["库存", "仓库", "销量", "补货", "耗尽", "缺货", "还能撑"],
    source: "builtin",
  },
  {
    version: 1,
    id: "budget-burn",
    title: "项目预算燃尽",
    category: "商业决策",
    question: "按当前花费速度，项目预算还能支撑多少天？",
    modelType: "inventory",
    parameters: [
      p("initialStock", "剩余预算", "元", 0, 10000000, 1000, 500000),
      p("dailyInflow", "每日新增预算", "元", 0, 100000, 500, 0),
      p("dailyOutflow", "每日花费", "元", 100, 500000, 500, 15000),
      p("duration", "观察天数", "天", 1, 365, 1, 60),
    ],
    metrics: [
      m("budget-final", "期末余额", "finalValue", "currency", "元"),
      m("budget-days", "预计可支撑", "depletionTime", "duration", "天"),
      m("budget-net", "每日净变化", "netDailyChange", "currency", "元"),
    ],
    chart: { type: "area", xLabel: "天", yLabel: "预算 元", series: ["value"] },
    explanation: explanation(
      "每日余额 = 上日余额 + 新增预算 − 每日花费，最低为零",
      ["每日花费保持不变", "未包含一次性大额支出"],
      "用于观察预算燃尽速度，不替代财务预算。",
    ),
    keywords: ["项目", "预算", "花费", "燃尽", "成本", "资金", "能撑多久"],
    source: "builtin",
  },
  {
    version: 1,
    id: "event-attendance",
    title: "活动到场漏斗",
    category: "商业决策",
    question: "从曝光、报名到最终到场，活动能来多少人？",
    modelType: "funnel",
    parameters: [
      p("audience", "活动曝光", "人", 100, 1000000, 100, 20000),
      p("rate1", "报名转化率", "%", 1, 100, 1, 8),
      p("rate2", "报名到场率", "%", 1, 100, 1, 65),
    ],
    metrics: [
      m("attendance-final", "预计到场", "finalValue", "number", "人"),
      m("attendance-rate", "整体到场率", "overallRate", "percent"),
    ],
    chart: { type: "funnel", xLabel: "阶段", yLabel: "人数", series: ["value"] },
    explanation: explanation(
      "预计到场 = 活动曝光 × 报名转化率 × 报名到场率",
      ["报名和到场比例保持稳定", "未考虑重复曝光和临时扩容"],
      "用于活动规模预估，实际到场受渠道和天气等因素影响。",
    ),
    keywords: ["活动", "报名", "到场", "曝光", "参会", "人数", "转化"],
    source: "builtin",
    stageLabels: ["曝光", "报名", "到场"],
  },
  {
    version: 1,
    id: "game-progression",
    title: "游戏数值成长曲线",
    category: "游戏产品",
    question: "按当前经验获取速度，玩家多久能够达到目标等级？",
    modelType: "linear",
    parameters: [
      p("initial", "当前累计经验", "XP", 0, 1000000, 100, 5000),
      p("rate", "每日获取经验", "XP", 100, 100000, 100, 2500),
      p("duration", "观察天数", "天", 1, 365, 1, 30),
    ],
    metrics: [
      m("progression-final", "期末累计经验", "finalValue", "number", "XP"),
      m("progression-gain", "期间获得经验", "totalChange", "number", "XP"),
    ],
    chart: { type: "area", xLabel: "天", yLabel: "累计经验 XP", series: ["value"] },
    explanation: explanation(
      "累计经验 = 当前经验 + 每日经验获取 × 天数",
      ["每日经验获取速度不变", "未包含等级提高后的经验需求变化"],
      "用于快速观察成长节奏，不是完整数值平衡器。",
    ),
    keywords: ["游戏", "角色", "升级", "经验", "成长", "满级", "数值曲线"],
    source: "builtin",
  },
];

export const EXPERIMENTS = Object.freeze(library.map(item => Object.freeze(item)));

export function getExperiment(id) {
  const experiment = EXPERIMENTS.find(item => item.id === id);
  return experiment ? structuredClone(experiment) : null;
}
