export const ROLE_TEMPLATES = [
  {
    role: "策划",
    title: "锁定二阶段规则与体验参数",
    keywords: ["二阶段", "40%", "0.8 秒", "压迫感"],
    objective: "把阶段触发、前摇与表现强度写成唯一可执行规则。",
    inputs: ["体验复盘结论", "当前战斗配置"],
    outputs: ["二阶段规则表", "体验参数确认记录"],
    acceptanceCriteria: ["Boss 血量首次降至 40% 时触发二阶段", "大招前摇目标时长为 0.8 秒", "范围外内容不进入本次版本"],
    priority: "P0",
  },
  {
    role: "客户端",
    title: "实现二阶段状态切换与红屏控制",
    keywords: ["代码里能改", "红屏", "暂停恢复", "受击硬直", "按钮"],
    objective: "在所有战斗状态下可靠进入二阶段，并保持 HUD 可读。",
    inputs: ["二阶段规则表", "红屏曲线", "现有 Boss 状态机"],
    outputs: ["状态切换逻辑", "红屏后处理控制", "暂停恢复处理"],
    acceptanceCriteria: ["红屏总时长为 0.6 秒", "红屏从 0 增强到峰值后回落至 20%", "暂停恢复后红屏和阶段状态不重复触发", "战斗按钮在红屏期间保持可读"],
    priority: "P0",
  },
  {
    role: "特效",
    title: "制作阶段爆发与地面预警表现",
    keywords: ["特效", "红屏", "地面预警", "低端机"],
    objective: "增强二阶段爆发感，同时不遮挡技能伤害区域。",
    inputs: ["表现目标", "性能档位规范"],
    outputs: ["阶段爆发特效", "大招地面预警", "低档特效配置"],
    acceptanceCriteria: ["地面预警在 48px HUD 与战斗镜头下均可识别", "低档特效不能隐藏技能伤害区域"],
    priority: "P1",
  },
  {
    role: "音频",
    title: "交付阶段爆发音与前摇候选",
    keywords: ["音效", "爆发音", "前摇音"],
    objective: "提供能区分阶段进入和大招蓄力的音频反馈。",
    inputs: ["阶段进入时间点", "大招前摇动画"],
    outputs: ["阶段爆发音", "前摇音候选 A/B"],
    acceptanceCriteria: ["阶段进入音与状态切换同步", "两个前摇候选使用同一响度基准供周四评审"],
    priority: "P1",
  },
  {
    role: "动画",
    title: "调整大招前摇动画可读性",
    keywords: ["前摇", "蓄力", "0.8 秒"],
    objective: "让玩家在伤害发生前明确识别大招蓄力。",
    inputs: ["大招动作", "0.8 秒前摇目标"],
    outputs: ["调整后的前摇动画", "事件时间点"],
    acceptanceCriteria: ["关键蓄力姿势在伤害前至少保留 0.3 秒", "动画事件与地面预警、音频使用同一触发点"],
    priority: "P1",
  },
  {
    role: "QA",
    title: "验证二阶段表现与异常恢复",
    keywords: ["QA", "暂停恢复", "低端机", "受击硬直", "帧率"],
    objective: "覆盖正常、边界、恢复、兼容与性能场景。",
    inputs: ["可测试版本", "支持设备列表", "二阶段验收标准"],
    outputs: ["验收记录", "缺陷清单", "性能数据"],
    acceptanceCriteria: ["正常和异常路径均只进入一次二阶段", "中端 Android 战斗帧率不低于 45 FPS", "所有 P0 验收项有截图或录屏证据"],
    priority: "P0",
  },
];

export const TEST_TEMPLATES = [
  {
    type: "functional",
    title: "血量阈值触发二阶段",
    keywords: ["40%", "二阶段"],
    preconditions: ["Boss 处于一阶段", "Boss 血量高于 40%"],
    steps: ["持续造成伤害使血量首次降至 40%", "观察状态、红屏、特效和音频"],
    expected: ["只进入一次二阶段", "红屏、爆发特效和音频在同一次状态切换中触发"],
  },
  {
    type: "boundary",
    title: "受击硬直跨阈值",
    keywords: ["受击硬直"],
    preconditions: ["Boss 处于受击硬直", "本次伤害使血量跨过 40%"],
    steps: ["结算跨阈值伤害", "等待硬直结束"],
    expected: ["不会丢失二阶段切换", "阶段表现不会重复播放"],
  },
  {
    type: "recovery",
    title: "阶段表现期间暂停恢复",
    keywords: ["暂停恢复"],
    preconditions: ["Boss 即将进入二阶段"],
    steps: ["红屏过程中暂停", "恢复游戏并继续战斗"],
    expected: ["阶段状态正确恢复", "红屏不会卡住或重新从头触发"],
  },
  {
    type: "compatibility",
    title: "低端机表现降级",
    keywords: ["低端机", "低档"],
    preconditions: ["切换到低档特效"],
    steps: ["进入二阶段", "触发大招前摇"],
    expected: ["伤害区域保持清晰", "关键音频和前摇提示不被关闭"],
  },
  {
    type: "performance",
    title: "中端 Android 战斗帧率",
    keywords: ["45 FPS", "中端 Android"],
    preconditions: ["使用目标中端 Android 设备", "开启标准特效"],
    steps: ["连续触发二阶段和大招", "记录 30 秒帧率"],
    expected: ["战斗帧率不低于 45 FPS", "无持续卡顿或后处理残留"],
  },
  {
    type: "functional",
    title: "红屏期间 HUD 可读性",
    keywords: ["按钮", "UI"],
    preconditions: ["HUD 和战斗按钮可见"],
    steps: ["触发二阶段红屏", "检查按钮文字、冷却和可点击区域"],
    expected: ["按钮内容保持可辨认", "红屏不改变按钮交互区域"],
  },
];
