const STORAGE_KEY = "planmap.hub-demo.v2";
const MODEL_KEY = "planmap.model-settings.v1";
const palettes = ["#287fd1", "#16a085", "#eb8c38", "#d95872", "#775ec7"];
const layoutLabels = { mindmap: "左右脑图", right: "横向脑图", tree: "树状图", fishbone: "鱼骨图", logic: "逻辑结构", timeline: "时间轴" };
const providerDefaults = {
  demo: { endpoint: "", model: "" },
  ollama: { endpoint: "http://localhost:11434/v1", model: "qwen2.5:7b" },
  lmstudio: { endpoint: "http://localhost:1234/v1", model: "local-model" },
  localai: { endpoint: "http://localhost:8080/v1", model: "qwen2.5-7b-instruct" },
  openai: { endpoint: "https://api.openai.com/v1", model: "gpt-4.1-mini" },
};

function node(id, title, children = [], color = "") { return { id, title, children, color }; }
function starterMap(title = "新品发布会策划") {
  return node("root", title, [
    node("goal", "目标与主题", [node("goal-1", "核心目标"), node("goal-2", "主题概念")]),
    node("audience", "受众洞察", [node("audience-1", "核心人群"), node("audience-2", "参与动机")]),
    node("content", "内容与体验", [node("content-1", "产品亮点"), node("content-2", "互动环节")]),
    node("spread", "传播节奏", [node("spread-1", "预热阶段"), node("spread-2", "引爆阶段")]),
  ]);
}
const festivalMap = () => node("root", "校园音乐节策划", [
  node("theme", "主题与目标", [node("theme-1", "青春共鸣"), node("theme-2", "校园品牌")]),
  node("people", "受众洞察", [node("people-1", "在校学生"), node("people-2", "社团与校友")]),
  node("program", "节目与体验", [node("program-1", "乐队舞台"), node("program-2", "社团互动"), node("program-3", "市集打卡")]),
  node("promotion", "传播节奏", [node("promotion-1", "社群预热"), node("promotion-2", "短视频挑战"), node("promotion-3", "现场直播")]),
  node("delivery", "执行保障", [node("delivery-1", "场地与设备"), node("delivery-2", "人员排班"), node("delivery-3", "风险预案")]),
]);

const state = { root: starterMap(), selectedId: null, theme: "azure", layout: "mindmap", view: "map", scale: 1, history: [], future: [], presentIndex: 0, replyIndex: 0, provider: "demo", endpoint: "", model: "", apiKey: "" };
const ui = Object.fromEntries(["messages","chatScroll","chatInput","sendButton","selectionChip","nodesLayer","connections","mapStage","canvasViewport","nodeCount","documentTitle","undoButton","redoButton","settingsBackdrop","exportBackdrop","modeButton","zoomValue","toast","outlineList","mapView","outlineView","presentView","presentTitle","presentContent","presentProgress","presentPrev","presentNext","modelFields","modelEndpoint","modelName","modelKey","modelNote"].map((id) => [id, document.getElementById(id)]));

function clone(value) { return JSON.parse(JSON.stringify(value)); }
function walk(current, visit, parent = null, depth = 0) { visit(current, parent, depth); current.children.forEach((child) => walk(child, visit, current, depth + 1)); }
function flatten() { const items = []; walk(state.root, (item, parent, depth) => items.push({ item, parent, depth })); return items; }
function findNode(id) { let found; walk(state.root, (item) => { if (item.id === id) found = item; }); return found; }
function countNodes() { return flatten().length; }
function uniqueId(prefix = "node") { return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2, 7)}`; }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify({ root: state.root, theme: state.theme, layout: state.layout })); }
function saveModel() { localStorage.setItem(MODEL_KEY, JSON.stringify({ provider: state.provider, endpoint: state.endpoint, model: state.model })); }
function commit(nextRoot) { state.history.push(clone(state.root)); state.history = state.history.slice(-30); state.future = []; state.root = nextRoot; state.selectedId = null; save(); render(); }
function setLayout(layout, announce = true) { if (!layoutLabels[layout]) return; state.layout = layout; save(); render(); requestAnimationFrame(centerMap); if (announce) showToast(`已切换为${layoutLabels[layout]}`); }

function nodeWidth(item) { return item.id === state.root.id ? 186 : 158; }
function nodeRows(item) { return Math.max(1, Math.ceil([...item.title].length / (item.id === state.root.id ? 9 : 8))); }
function nodeHeight(item, depth = 2) { return Math.max(item.id === state.root.id ? 64 : depth === 1 ? 52 : 46, 20 + nodeRows(item) * (item.id === state.root.id ? 23 : 22)); }
function leafSpan(item) { return item.children.length ? Math.max(nodeHeight(item), item.children.reduce((sum, child) => sum + leafSpan(child), 0)) : nodeHeight(item); }
function maxDepth(item, depth = 0) { return item.children.reduce((value, child) => Math.max(value, maxDepth(child, depth + 1)), depth); }

function rawPositions() {
  const points = new Map(); const root = state.root; const margin = 80;
  if (state.layout === "tree") {
    let cursorX = 80; const gapX = 200; const levelGap = 52; const levelHeights = [];
    walk(root, (item, _parent, depth) => { levelHeights[depth] = Math.max(levelHeights[depth] || 0, nodeHeight(item, depth)); });
    const levelY = [130]; for (let depth = 1; depth < levelHeights.length; depth++) levelY[depth] = levelY[depth - 1] + levelHeights[depth - 1] + levelGap;
    const place = (item, depth) => { const childXs = item.children.map((child) => place(child, depth + 1)); const x = childXs.length ? (childXs[0] + childXs.at(-1)) / 2 : cursorX; if (!childXs.length) cursorX += gapX; points.set(item.id, { x, y: levelY[depth] }); return x; };
    place(root, 0); const last = levelHeights.length - 1; return { points, width: Math.max(1100, cursorX + 80), height: Math.max(760, levelY[last] + levelHeights[last] + 120), rootPoint: points.get(root.id) };
  }
  if (state.layout === "timeline") {
    const topRow = 112 + Math.max(0, root.children.length - 1) * 12; const levelGap = 66; const branchGap = 52; const subtreeGap = 28; const levelHeights = [];
    root.children.forEach((branch) => walk(branch, (item, _parent, depth) => { const actualDepth = depth + 1; levelHeights[actualDepth] = Math.max(levelHeights[actualDepth] || 0, nodeHeight(item, actualDepth)); }));
    const topRowHeight = Math.max(nodeHeight(root, 0), levelHeights[1] || 0); const levelTops = [topRow, topRow]; let levelTop = topRow + topRowHeight + levelGap;
    for (let depth = 2; depth <= maxDepth(root); depth += 1) { levelTops[depth] = levelTop; levelTop += (levelHeights[depth] || 46) + levelGap; }
    const subtreeWidth = (item, depth) => Math.max(nodeWidth(item) + subtreeGap, item.children.reduce((sum, child) => sum + subtreeWidth(child, depth + 1), 0));
    points.set(root.id, { x: margin, y: topRow }); let branchLeft = margin + nodeWidth(root) + 86;
    const place = (item, depth, left) => { const span = subtreeWidth(item, depth); const childrenWidth = item.children.reduce((sum, child) => sum + subtreeWidth(child, depth + 1), 0); let center = left + span / 2; if (item.children.length) { let childLeft = left + (span - childrenWidth) / 2; const centers = item.children.map((child) => { const childCenter = place(child, depth + 1, childLeft); childLeft += subtreeWidth(child, depth + 1); return childCenter; }); center = (centers[0] + centers.at(-1)) / 2; } points.set(item.id, { x: center - nodeWidth(item) / 2, y: levelTops[depth] ?? levelTop }); return center; };
    root.children.forEach((item) => { place(item, 1, branchLeft); branchLeft += subtreeWidth(item, 1) + branchGap; }); return { points, width: Math.max(1100, branchLeft + 80), height: Math.max(760, levelTop + 90), rootPoint: points.get(root.id) };
  }
  if (state.layout === "fishbone") {
    const rootY = 450; const branchGap = 260; const depthGap = 230; const rootHeight = nodeHeight(root, 0); let cursorX = 350; let farX = cursorX; let minY = rootY; let maxY = rootY;
    const branchData = root.children.map((branch, branchIndex) => ({ branch, branchIndex, side: branchIndex % 2 === 0 ? -1 : 1, height: nodeHeight(branch, 1) }));
    const maxTopHalf = Math.max(0, ...branchData.filter((item) => item.side < 0).map((item) => item.height / 2)); const maxBottomHalf = Math.max(0, ...branchData.filter((item) => item.side > 0).map((item) => item.height / 2));
    const requiredHalf = Math.max(rootHeight / 2, maxTopHalf + maxBottomHalf + 110, rootHeight / 2 + 48 + Math.max(0, root.children.length - 1) * 12);
    points.set(root.id, { x: margin, y: rootY + requiredHalf - rootHeight / 2 });
    branchData.forEach(({ branch, branchIndex, side, height: branchHeight }) => {
      const baseX = cursorX; let distance = requiredHalf + branchHeight / 2 + 28 + Math.floor(branchIndex / 2) * 96; points.set(branch.id, { x: baseX, y: rootY + requiredHalf + side * distance }); farX = Math.max(farX, baseX);
      const place = (item, depth) => { const height = nodeHeight(item, depth + 1); distance += height / 2 + 42; const x = baseX + depth * depthGap; const y = rootY + requiredHalf + side * distance; points.set(item.id, { x, y }); farX = Math.max(farX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y + height); distance += height / 2; item.children.forEach((child) => place(child, depth + 1)); };
      branch.children.forEach((child) => place(child, 1));
      cursorX = baseX + Math.max(1, maxDepth(branch)) * depthGap + branchGap;
    });
    return { points, width: Math.max(1200, farX + 300), height: Math.max(850, maxY + Math.max(100, Math.abs(minY))), rootPoint: points.get(root.id) };
  }
  const branches = root.children; const rightOnly = state.layout === "right" || state.layout === "logic";
  const left = rightOnly ? [] : branches.filter((_, index) => index % 2 === 0); const right = rightOnly ? branches : branches.filter((_, index) => index % 2 === 1);
  const leftDepth = left.reduce((value, item) => Math.max(value, maxDepth(item, 1)), 0); const rightDepth = right.reduce((value, item) => Math.max(value, maxDepth(item, 1)), 0);
  const gapX = state.layout === "logic" ? 270 : 245; const gapY = 76; const rootX = rightOnly ? margin : margin + Math.max(1, leftDepth) * gapX;
  const leftSpan = left.reduce((sum, item) => sum + leafSpan(item) + gapY / 2, 0); const rightSpan = right.reduce((sum, item) => sum + leafSpan(item) + gapY / 2, 0); const totalSpan = Math.max(nodeHeight(root), leftSpan, rightSpan); const rootY = margin + totalSpan / 2 - nodeHeight(root) / 2;
  points.set(root.id, { x: rootX, y: rootY });
  const placeSide = (items, side, sideSpan) => { let cursorY = margin + (totalSpan - sideSpan) / 2; const place = (item, depth) => { const start = cursorY; const childYs = item.children.map((child) => place(child, depth + 1)); const height = nodeHeight(item, depth); const y = childYs.length ? (childYs[0] + childYs.at(-1)) / 2 : cursorY; cursorY = Math.max(cursorY + height + gapY / 2, start + leafSpan(item) + gapY / 2); points.set(item.id, { x: rootX + (side === "left" ? -1 : 1) * depth * gapX, y }); return y; }; items.forEach((item) => place(item, 1)); };
  placeSide(left, "left", leftSpan); placeSide(right, "right", rightSpan);
  return { points, width: Math.max(1100, rootX + Math.max(1, rightDepth) * gapX + 230), height: Math.max(760, margin * 2 + totalSpan), rootPoint: points.get(root.id) };
}

function positions() {
  const raw = rawPositions(); let minX = Infinity; let minY = Infinity; let maxX = 0; let maxY = 0;
  walk(state.root, (item, _parent, depth) => { const point = raw.points.get(item.id); if (!point) return; const width = nodeWidth(item); const height = nodeHeight(item, depth); minX = Math.min(minX, point.x); minY = Math.min(minY, point.y); maxX = Math.max(maxX, point.x + width); maxY = Math.max(maxY, point.y + height); });
  const shiftX = minX < 70 ? 70 - minX : 0; const shiftY = minY < 70 ? 70 - minY : 0;
  if (shiftX || shiftY) raw.points.forEach((point) => { point.x += shiftX; point.y += shiftY; });
  return { ...raw, width: Math.max(raw.width + shiftX, maxX + shiftX + 90), height: Math.max(raw.height + shiftY, maxY + shiftY + 90), rootPoint: raw.points.get(state.root.id) };
}

function portOffset(index, count, extent) { return count <= 1 ? 0 : -(extent - 18) / 2 + (extent - 18) * index / (count - 1); }
function pathFor(parent, item, from, to, depth) {
  const siblingIndex = Math.max(0, parent.children.indexOf(item)); const siblingCount = Math.max(1, parent.children.length);
  const fromWidth = nodeWidth(parent); const toWidth = nodeWidth(item); const fromDepth = parent.id === state.root.id ? 0 : Math.max(1, depth - 1);
  const fromHeight = nodeHeight(parent, fromDepth); const toHeight = nodeHeight(item, depth);
  if (state.layout === "tree") { const aX = from.x + fromWidth / 2 + portOffset(siblingIndex, siblingCount, fromWidth); const aY = from.y + fromHeight; const bX = to.x + toWidth / 2; const bY = to.y; const curve = Math.max(28, Math.min(96, Math.abs(bY - aY) * .52)); return `M ${aX} ${aY} C ${aX} ${aY + curve}, ${bX} ${bY - curve}, ${bX} ${bY}`; }
  const fromCenterY = from.y + fromHeight / 2; const toCenterY = to.y + toHeight / 2;
  if (state.layout === "timeline") { if (parent.id === state.root.id) { const aX = from.x + fromWidth / 2 + portOffset(siblingIndex, siblingCount, fromWidth); const aY = from.y; const bX = to.x + toWidth / 2; const bY = to.y; const laneY = aY - (24 + siblingIndex * 12); return `M ${aX} ${aY} C ${aX} ${laneY}, ${aX} ${laneY}, ${aX} ${laneY} C ${aX} ${laneY}, ${bX} ${laneY}, ${bX} ${laneY} C ${bX} ${laneY}, ${bX} ${bY}, ${bX} ${bY}`; } const direction = toCenterY >= fromCenterY ? 1 : -1; const aX = from.x + fromWidth / 2 + portOffset(siblingIndex, siblingCount, fromWidth); const aY = direction > 0 ? from.y + fromHeight : from.y; const bX = to.x + toWidth / 2; const bY = direction > 0 ? to.y : to.y + toHeight; const laneY = aY + direction * (20 + siblingIndex * 10); return `M ${aX} ${aY} C ${aX} ${laneY}, ${aX} ${laneY}, ${aX} ${laneY} C ${aX} ${laneY}, ${bX} ${laneY}, ${bX} ${laneY} C ${bX} ${laneY}, ${bX} ${bY}, ${bX} ${bY}`; }
  if (state.layout === "fishbone") { const direction = toCenterY < fromCenterY ? -1 : 1; const fromX = parent.id === state.root.id ? from.x + fromWidth / 2 + portOffset(siblingIndex, siblingCount, fromWidth) : from.x + fromWidth; const fromY = parent.id === state.root.id ? (direction < 0 ? from.y : from.y + fromHeight) : fromCenterY + portOffset(siblingIndex, siblingCount, fromHeight); const toX = to.x; const laneX = parent.id === state.root.id ? toX - 28 - siblingIndex * 4 : Math.min(toX - 18, Math.max(fromX + 6, from.x + fromWidth + 12 + siblingIndex * 8)); if (parent.id === state.root.id) { const laneY = fromY + direction * (24 + siblingIndex * 12); return `M ${fromX} ${fromY} C ${fromX} ${laneY}, ${fromX} ${laneY}, ${fromX} ${laneY} C ${fromX} ${laneY}, ${laneX} ${laneY}, ${laneX} ${laneY} C ${laneX} ${laneY}, ${laneX} ${toCenterY}, ${laneX} ${toCenterY} C ${laneX} ${toCenterY}, ${toX} ${toCenterY}, ${toX} ${toCenterY}`; } return `M ${fromX} ${fromY} C ${laneX} ${fromY}, ${laneX} ${fromY}, ${laneX} ${fromY} C ${laneX} ${fromY}, ${laneX} ${toCenterY}, ${laneX} ${toCenterY} C ${laneX} ${toCenterY}, ${toX} ${toCenterY}, ${toX} ${toCenterY}`; }
  const rightward = to.x >= from.x; const direction = rightward ? 1 : -1; const fromX = rightward ? from.x + fromWidth : from.x; const toX = rightward ? to.x : to.x + toWidth; const fromY = fromCenterY + portOffset(siblingIndex, siblingCount, fromHeight); const toY = toCenterY; const curve = Math.max(30, Math.min(118, Math.abs(toX - fromX) * .5));
  return `M ${fromX} ${fromY} C ${fromX + direction * curve} ${fromY}, ${toX - direction * curve} ${toY}, ${toX} ${toY}`;
}
function renderConnections(layout) { const paths = []; walk(state.root, (item, parent, depth) => { if (!parent) return; const from = layout.get(parent.id); const to = layout.get(item.id); if (from && to) paths.push(`<path data-parent="${parent.id}" data-child="${item.id}" d="${pathFor(parent, item, from, to, depth)}" />`); }); ui.connections.innerHTML = paths.join(""); }
function nodeTools(item) { const base = `<span class="node-tools"><button data-tool="rename" title="改名">✎</button><button data-tool="add" title="添加子节点">＋</button><button data-tool="color" title="切换节点颜色">◉</button>`; return item.id === "root" ? `${base}</span>` : `${base}<button data-tool="delete" class="danger" title="删除节点">×</button></span>`; }

function renderMap() {
  const mapLayout = positions(); const layout = mapLayout.points; ui.mapStage.style.width = `${mapLayout.width}px`; ui.mapStage.style.height = `${mapLayout.height}px`; ui.mapStage.dataset.rootX = mapLayout.rootPoint.x; ui.mapStage.dataset.rootY = mapLayout.rootPoint.y; ui.mapStage.dataset.layout = state.layout; ui.nodesLayer.innerHTML = "";
  walk(state.root, (item, _parent, depth) => { const point = layout.get(item.id); if (!point) return; const element = document.createElement("button"); element.type = "button"; element.className = `map-node level-${Math.min(depth, 2)} ${item.id === "root" ? "root" : ""} ${item.id === state.selectedId ? "selected" : ""}`; element.dataset.id = item.id; element.style.left = `${point.x}px`; element.style.top = `${point.y}px`; element.style.width = `${nodeWidth(item)}px`; element.style.height = `${nodeHeight(item, depth)}px`; element.style.setProperty("--node-color", branchColor(item)); const label = document.createElement("span"); label.textContent = item.title; element.append(label); element.insertAdjacentHTML("beforeend", nodeTools(item)); ui.nodesLayer.append(element); });
  renderConnections(layout); ui.mapStage.style.transform = `scale(${state.scale})`; ui.zoomValue.textContent = `${Math.round(state.scale * 100)}%`;
}
function renderOutline() { ui.outlineList.innerHTML = ""; walk(state.root, (item, _parent, depth) => { const button = document.createElement("button"); button.type = "button"; button.className = `outline-item ${item.id === state.selectedId ? "selected" : ""}`; button.dataset.id = item.id; button.style.paddingLeft = `${10 + depth * 24}px`; button.style.setProperty("--node-color", branchColor(item)); const dot = document.createElement("i"); const title = document.createElement("b"); title.textContent = item.title; const count = document.createElement("small"); count.textContent = item.children.length ? `${item.children.length} 项` : ""; button.append(dot, title, count); ui.outlineList.append(button); }); }
function renderPresentation() { const branches = state.root.children.length ? state.root.children : [state.root]; state.presentIndex = Math.min(state.presentIndex, branches.length - 1); const branch = branches[state.presentIndex]; ui.presentProgress.textContent = `${state.presentIndex + 1} / ${branches.length}`; ui.presentTitle.textContent = branch.title; ui.presentContent.innerHTML = ""; const list = document.createElement("ul"); const items = branch.children.length ? branch.children : [branch]; items.forEach((item) => { const li = document.createElement("li"); li.textContent = item.title; list.append(li); }); ui.presentContent.append(list); ui.presentPrev.disabled = state.presentIndex === 0; ui.presentNext.disabled = state.presentIndex === branches.length - 1; }
function render() {
  renderMap(); renderOutline(); renderPresentation(); ui.nodeCount.textContent = `共 ${countNodes()} 个节点 · ${layoutLabels[state.layout]}自动排版`; ui.documentTitle.value = state.root.title; ui.undoButton.disabled = state.history.length === 0; ui.redoButton.disabled = state.future.length === 0;
  const selected = findNode(state.selectedId); ui.selectionChip.hidden = !selected; ui.selectionChip.querySelector("span").textContent = selected ? `@ ${selected.title}` : ""; document.querySelector(".app-shell").className = `app-shell theme-${state.theme}`;
  document.querySelectorAll("[data-layout]").forEach((button) => button.classList.toggle("active", button.dataset.layout === state.layout)); document.querySelectorAll("[data-view]").forEach((button) => button.classList.toggle("active", button.dataset.view === state.view)); [ui.mapView, ui.outlineView, ui.presentView].forEach((panel) => panel.classList.remove("active")); ({ map: ui.mapView, outline: ui.outlineView, present: ui.presentView })[state.view].classList.add("active");
}

function addMessage(role, text, thinking = false) { const row = document.createElement("div"); row.className = `message-row ${role}${thinking ? " thinking" : ""}`; const avatar = document.createElement("span"); avatar.textContent = role === "user" ? "你" : "✦"; const content = document.createElement("p"); content.textContent = text; row.append(avatar, content); ui.messages.append(row); ui.chatScroll.scrollTop = ui.chatScroll.scrollHeight; return row; }
function addChildren(target, titles) { const next = clone(state.root); let nodeToEdit; walk(next, (item) => { if (item.id === target.id) nodeToEdit = item; }); titles.forEach((title) => nodeToEdit.children.push(node(uniqueId(target.id), title))); return next; }
function removeFromTree(root, id) { root.children = root.children.filter((child) => child.id !== id); root.children.forEach((child) => removeFromTree(child, id)); }
function nextReply(templates, details) { const template = templates[state.replyIndex++ % templates.length]; return template.replace("{details}", details); }
function findTextCandidates(source) { const query = source.trim(); const all = flatten().map(({ item }) => item); const exact = all.filter((item) => item.title === query); if (exact.length) return exact; return all.filter((item) => item.title.includes(query) || query.includes(item.title)); }
function replaceTextGlobally(source, target) { const candidates = findTextCandidates(source); if (candidates.length !== 1) return { candidates, changed: false }; const next = clone(state.root); walk(next, (item) => { if (item.id === candidates[0].id) item.title = target; }); commit(next); return { candidates, changed: true }; }
function parseReplacement(message) { const cleaned = message.trim().replace(/[。！!]+$/, ""); const match = cleaned.match(/^(?:请)?(?:把|将)[“"']?(.+?)[”"']?(?:替换成|改成|换成)[“"']?(.+?)[”"']?$/); return match ? { source: match[1].trim(), target: match[2].trim() } : null; }
function matchNamedNode(message) { const candidates = flatten().map(({ item }) => item).filter((item) => message.includes(item.title)); return candidates.sort((a, b) => b.title.length - a.title.length)[0]; }
function layoutFromMessage(message) { const rules = [["fishbone", /鱼骨/], ["timeline", /时间轴|时间线/], ["tree", /树状|组织结构/], ["logic", /逻辑|括号/], ["right", /横向|向右/], ["mindmap", /左右|平衡|标准脑图/]]; return rules.find(([, pattern]) => pattern.test(message))?.[0]; }

function applyPrompt(message) {
  const normalized = message.replace(/\s+/g, ""); const selected = findNode(state.selectedId);
  const replacement = parseReplacement(message);
  if (replacement && selected && /^(这个|此节点|选中节点)$/.test(replacement.source)) { const next = clone(state.root); walk(next, (item) => { if (item.id === selected.id) item.title = replacement.target; }); commit(next); return nextReply(["已把选中节点改为“{details}”。", "节点命名已更新为“{details}”。", "改好了，现在显示“{details}”。"], replacement.target); }
  if (replacement) { const result = replaceTextGlobally(replacement.source, replacement.target); if (result.changed) return nextReply(["已找到原文并替换：{details}。", "文字已经精准更新：{details}，版面也同步整理好了。", "完成，{details}。其他节点没有改动。"], `“${replacement.source}” → “${replacement.target}”`); if (!result.candidates.length) return `没有找到包含“${replacement.source}”的节点。你可以换用节点里的完整文字再试一次。`; return `找到 ${result.candidates.length} 个可能的节点：${result.candidates.slice(0, 5).map((item) => `“${item.title}”`).join("、")}。请把原文字说完整，我再准确替换。`; }
  const requestedLayout = layoutFromMessage(message);
  if (requestedLayout && /切换|换成|改成|结构|布局|排版|使用/.test(normalized)) { setLayout(requestedLayout, false); return nextReply(["已切换为{details}，所有节点已重新计算位置。", "好的，整张图现在是{details}，内容层级保持不变。", "结构调整完成：{details}。你可以继续用一句话改内容。"], layoutLabels[requestedLayout]); }
  if (/校园.*音乐节|音乐节/.test(normalized)) { commit(festivalMap()); return nextReply(["校园音乐节脑图已生成，{details}", "新策划已经铺开，{details}", "我重构好了这张图，{details}"], "主题、受众、节目、传播和执行五条主线都已自动排版。"); }
  if (/风险|预案/.test(normalized)) { const target = selected || matchNamedNode(message) || findNode("delivery") || state.root; commit(addChildren(target, ["天气备选方案", "安全与医疗", "舆情响应"])); return nextReply(["已在“{details}”下补齐天气、安全和舆情三类预案。", "风险分支已经补全，位置在“{details}”下。", "“{details}”现在多了三项可执行的风险保障。"], target.title); }
  if (/预算|资源/.test(normalized)) { const next = addChildren(state.root, ["预算与资源"]); const branch = next.children.at(-1); branch.children = [node(uniqueId("budget"), "场地与设备"), node(uniqueId("budget"), "人员与宣传"), node(uniqueId("budget"), "机动预算")]; commit(next); return nextReply(["预算与资源已加入，{details}", "投入项已经单独成章，{details}", "这部分补好了：{details}"], "场地、人员宣传和机动预算都已拆分。"); }
  if (/删除|移除|去掉/.test(normalized)) { const target = selected || matchNamedNode(message); if (target && target.id !== "root") { const next = clone(state.root); removeFromTree(next, target.id); commit(next); return nextReply(["已删除“{details}”，其余分支自动收拢。", "“{details}”及其下级内容已经移除。", "处理好了，“{details}”已从脑图中清除。"], target.title); } return "请直接说要删除的文字，例如“删除互动环节”，不需要先选择节点。"; }
  if (/改成|重命名/.test(normalized) && selected) { const title = message.split(/改成|重命名为/).at(-1).replace(/[“”"。]/g, "").trim() || "新名称"; const next = clone(state.root); walk(next, (item) => { if (item.id === selected.id) item.title = title; }); commit(next); return nextReply(["已把选中节点改为“{details}”。", "节点命名已更新为“{details}”。", "改好了，现在显示“{details}”。"], title); }
  if (/展开|补充|细化|可执行/.test(normalized)) { const target = selected || matchNamedNode(message) || state.root.children[0]; commit(addChildren(target, ["负责人和截止时间", "验收标准", "下一步动作"])); return nextReply(["已把“{details}”展开为三项可执行动作。", "“{details}”已经补充负责人、验收标准和下一步。", "我继续细化了“{details}”，并保持自动排版。"], target.title); }
  if (/精简|收敛|压缩/.test(normalized)) { const next = clone(state.root); walk(next, (item) => { if (item.children.length > 3) item.children = item.children.slice(0, 3); }); commit(next); return `已从全局收敛重复分支，目前保留 ${countNodes()} 个核心节点。`;
  }
  return nextReply(["我已经理解这条要求。你可以直接指定原文替换、切换结构，或说要补充的主题，不必先选节点。", "这张图支持整体对话调整。试试“把核心目标改成品牌破圈”或“切换成鱼骨图”。", `当前是${layoutLabels[state.layout]}，共有 ${countNodes()} 个节点。告诉我哪段文字或哪个主题要调整即可。`], "");
}

function normalizeEndpoint(value) { const endpoint = value.trim().replace(/\/+$/, ""); return endpoint.endsWith("/chat/completions") ? endpoint : `${endpoint}/chat/completions`; }
function applyModelOperations(result) { if (!result || typeof result.reply !== "string" || !Array.isArray(result.operations)) throw new Error("模型没有返回可识别的脑图操作。"); let next = clone(state.root); let changed = false; for (const operation of result.operations) { if (operation.type === "rename" && typeof operation.nodeId === "string" && typeof operation.title === "string") { walk(next, (item) => { if (item.id === operation.nodeId) { item.title = operation.title; changed = true; } }); } if (operation.type === "add-child" && typeof operation.parentId === "string" && typeof operation.title === "string") { let parent; walk(next, (item) => { if (item.id === operation.parentId) parent = item; }); if (parent) { parent.children.push(node(uniqueId(parent.id), operation.title)); changed = true; } } if (operation.type === "delete" && typeof operation.nodeId === "string" && operation.nodeId !== "root") { const before = JSON.stringify(next); removeFromTree(next, operation.nodeId); changed ||= before !== JSON.stringify(next); } if (operation.type === "set-layout" && layoutLabels[operation.layout]) setLayout(operation.layout, false); } if (changed) commit(next); return result.reply; }
async function askCompatibleModel(message) {
  if (!state.endpoint.trim() || !state.model.trim()) throw new Error("请先在设置中填写 API 地址和模型名称。");
  const nodes = flatten().map(({ item }) => ({ id: item.id, title: item.title, children: item.children.map((child) => child.id) }));
  const system = `你是“思维导图快捷工具”的 AI 助手。根据用户要求返回严格 JSON：{"reply":"自然、具体的中文回复","operations":[{"type":"rename","nodeId":"ID","title":"新文字"}|{"type":"add-child","parentId":"ID","title":"文字"}|{"type":"delete","nodeId":"ID"}|{"type":"set-layout","layout":"mindmap|right|tree|fishbone|logic|timeline"}]}。没有操作时 operations 为空。不得输出 JSON 以外内容。当前节点：${JSON.stringify(nodes)}；选中节点：${state.selectedId || "无"}。`;
  const headers = { "Content-Type": "application/json" }; if (state.apiKey) headers.Authorization = `Bearer ${state.apiKey}`;
  const response = await fetch(normalizeEndpoint(state.endpoint), { method: "POST", headers, body: JSON.stringify({ model: state.model, temperature: 0.55, messages: [{ role: "system", content: system }, { role: "user", content: message }] }) });
  if (!response.ok) throw new Error(`模型连接失败（${response.status}）。请检查地址、模型名称与浏览器 CORS 设置。`);
  const payload = await response.json(); const content = payload.choices?.[0]?.message?.content; if (!content) throw new Error("模型没有返回内容。"); const clean = content.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, ""); return applyModelOperations(JSON.parse(clean));
}
async function send() { const message = ui.chatInput.value.trim(); if (!message) return; ui.chatInput.value = ""; addMessage("user", message); const thinkingTexts = ["正在定位相关节点…", "正在理解整体修改…", "正在重新组织脑图…"]; const thinking = addMessage("assistant", thinkingTexts[state.replyIndex % thinkingTexts.length], true); ui.sendButton.disabled = true; try { if (state.provider === "demo") await new Promise((resolve) => setTimeout(resolve, 420)); const reply = state.provider === "demo" ? applyPrompt(message) : await askCompatibleModel(message); thinking.remove(); addMessage("assistant", reply); } catch (error) { thinking.remove(); addMessage("assistant", error instanceof Error ? error.message : "处理失败，请重试。"); } finally { ui.sendButton.disabled = false; } }

function download(name, content, type = "text/plain") { const link = document.createElement("a"); const blob = content instanceof Blob ? content : new Blob([content], { type }); link.href = URL.createObjectURL(blob); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000); }
function markdown(item = state.root, depth = 1) { return `${"  ".repeat(depth - 1)}- ${item.title}\n${item.children.map((child) => markdown(child, depth + 1)).join("")}`; }
function showToast(text) { ui.toast.textContent = text; ui.toast.hidden = false; setTimeout(() => { ui.toast.hidden = true; }, 2100); }
function branchColor(item) { if (item.id === state.root.id) return getComputedStyle(document.querySelector(".app-shell")).getPropertyValue("--accent").trim() || palettes[0]; let index = 0; for (const branch of state.root.children) { let contains = false; walk(branch, (candidate) => { if (candidate.id === item.id) contains = true; }); if (contains) return item.color || palettes[index % palettes.length]; index++; } return item.color || palettes[0]; }
function exportCanvas() { const layout = positions(); const scale = 1.5; const canvas = document.createElement("canvas"); canvas.width = Math.ceil(layout.width * scale); canvas.height = Math.ceil(layout.height * scale); const context = canvas.getContext("2d"); context.scale(scale, scale); context.fillStyle = "#f6f9fc"; context.fillRect(0, 0, layout.width, layout.height); context.lineWidth = 2; context.strokeStyle = "#a9bdcc"; walk(state.root, (item, parent, depth) => { if (!parent) return; const from = layout.points.get(parent.id); const to = layout.points.get(item.id); const path = new Path2D(pathFor(parent, item, from, to, depth)); context.stroke(path); }); walk(state.root, (item, _parent, depth) => { const point = layout.points.get(item.id); const isRoot = item.id === state.root.id; const width = nodeWidth(item); const height = nodeHeight(item, depth); const color = branchColor(item); context.fillStyle = isRoot ? color : "#ffffff"; context.strokeStyle = color; context.lineWidth = isRoot ? 0 : 2; context.beginPath(); context.roundRect(point.x, point.y, width, height, isRoot ? 15 : 10); context.fill(); if (!isRoot) context.stroke(); context.fillStyle = isRoot ? "#ffffff" : "#33495b"; context.font = `${isRoot ? 700 : depth === 1 ? 650 : 500} ${isRoot ? 17 : depth === 1 ? 15 : 14}px "Microsoft YaHei", sans-serif`; context.textAlign = "center"; context.textBaseline = "middle"; drawTitle(context, item.title, point.x + width / 2, point.y + height / 2, width - 18, height - 10, isRoot ? 19 : 18); }); return canvas; }
function canvasBlob(canvas, type, quality) { return new Promise((resolve) => canvas.toBlob(resolve, type, quality)); }
function textLines(context, value, maxWidth) { const characters = [...value]; const lines = []; let line = ""; for (const character of characters) { const candidate = line + character; if (line && context.measureText(candidate).width > maxWidth) { lines.push(line); line = character; } else line = candidate; } if (line || lines.length === 0) lines.push(line); return lines; }
function drawTitle(context, title, centerX, centerY, maxWidth, maxHeight, lineHeight) { let lines = textLines(context, title, maxWidth); const availableLines = Math.max(1, Math.floor(maxHeight / lineHeight)); if (lines.length > availableLines) { const condensed = context.font.replace(/\b(1[0-9]|[2-9][0-9])px\b/, (_, size) => `${Math.max(7, Math.floor(Number(size) * availableLines / lines.length))}px`); context.font = condensed; lines = textLines(context, title, maxWidth); } const top = centerY - (lines.length - 1) * lineHeight / 2; lines.forEach((line, index) => context.fillText(line, centerX, top + index * lineHeight, maxWidth)); }
function bytesFromBase64(value) { const binary = atob(value); return Uint8Array.from(binary, (char) => char.charCodeAt(0)); }
function concatBytes(parts) { const length = parts.reduce((sum, part) => sum + part.length, 0); const output = new Uint8Array(length); let offset = 0; for (const part of parts) { output.set(part, offset); offset += part.length; } return output; }
function textBytes(value) { return new TextEncoder().encode(value); }
function pdfFromCanvas(canvas) { const jpeg = bytesFromBase64(canvas.toDataURL("image/jpeg", .92).split(",")[1]); const pageWidth = 842; const pageHeight = 595; const margin = 20; const ratio = Math.min((pageWidth - margin * 2) / canvas.width, (pageHeight - margin * 2) / canvas.height); const width = canvas.width * ratio; const height = canvas.height * ratio; const x = (pageWidth - width) / 2; const y = (pageHeight - height) / 2; const content = textBytes(`q ${width.toFixed(2)} 0 0 ${height.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm /Im0 Do Q`); const objects = [textBytes("<< /Type /Catalog /Pages 2 0 R >>"), textBytes("<< /Type /Pages /Kids [3 0 R] /Count 1 >>"), textBytes(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /XObject << /Im0 4 0 R >> >> /Contents 5 0 R >>`), concatBytes([textBytes(`<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`), jpeg, textBytes("\nendstream")]), concatBytes([textBytes(`<< /Length ${content.length} >>\nstream\n`), content, textBytes("\nendstream")])]; const parts = [textBytes("%PDF-1.4\n%\u00e2\u00e3\u00cf\u00d3\n")]; const offsets = [0]; let offset = parts[0].length; objects.forEach((object, index) => { offsets.push(offset); const part = concatBytes([textBytes(`${index + 1} 0 obj\n`), object, textBytes("\nendobj\n")]); parts.push(part); offset += part.length; }); const xrefOffset = offset; let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`; for (let index = 1; index <= objects.length; index++) xref += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`; parts.push(textBytes(`${xref}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`)); return new Blob(parts, { type: "application/pdf" }); }
const crcTable = Array.from({ length: 256 }, (_, value) => { let crc = value; for (let bit = 0; bit < 8; bit++) crc = (crc & 1) ? 0xedb88320 ^ (crc >>> 1) : crc >>> 1; return crc >>> 0; });
function crc32(bytes) { let crc = 0xffffffff; for (const byte of bytes) crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8); return (crc ^ 0xffffffff) >>> 0; }
function zipBytes(entries) { const local = []; const central = []; let offset = 0; for (const [name, value] of entries) { const nameBytes = textBytes(name); const data = typeof value === "string" ? textBytes(value) : value; const crc = crc32(data); const header = new Uint8Array(30 + nameBytes.length); const view = new DataView(header.buffer); view.setUint32(0, 0x04034b50, true); view.setUint16(4, 20, true); view.setUint16(6, 0x0800, true); view.setUint32(14, crc, true); view.setUint32(18, data.length, true); view.setUint32(22, data.length, true); view.setUint16(26, nameBytes.length, true); header.set(nameBytes, 30); local.push(header, data); const directory = new Uint8Array(46 + nameBytes.length); const directoryView = new DataView(directory.buffer); directoryView.setUint32(0, 0x02014b50, true); directoryView.setUint16(4, 20, true); directoryView.setUint16(6, 20, true); directoryView.setUint16(8, 0x0800, true); directoryView.setUint32(16, crc, true); directoryView.setUint32(20, data.length, true); directoryView.setUint32(24, data.length, true); directoryView.setUint16(28, nameBytes.length, true); directoryView.setUint32(42, offset, true); directory.set(nameBytes, 46); central.push(directory); offset += header.length + data.length; } const centralBytes = concatBytes(central); const end = new Uint8Array(22); const endView = new DataView(end.buffer); endView.setUint32(0, 0x06054b50, true); endView.setUint16(8, entries.length, true); endView.setUint16(10, entries.length, true); endView.setUint32(12, centralBytes.length, true); endView.setUint32(16, offset, true); return concatBytes([...local, centralBytes, end]); }
function xmindTopic(item) { return { id: item.id, class: "topic", title: item.title, ...(item.children.length ? { children: { attached: item.children.map(xmindTopic) } } : {}) }; }
function xmindArchive() { const sheetId = `sheet-${Date.now()}`; const content = JSON.stringify([{ id: sheetId, class: "sheet", title: state.root.title, rootTopic: xmindTopic(state.root) }]); const metadata = JSON.stringify({ creator: { name: "思维导图快捷工具", version: "2.0" }, activeSheetId: sheetId }); const manifest = JSON.stringify({ "file-entries": { "content.json": {}, "metadata.json": {}, "manifest.json": {} } }); return new Blob([zipBytes([["content.json", content], ["metadata.json", metadata], ["manifest.json", manifest]])], { type: "application/vnd.xmind.workbook" }); }
function safeName(value) { return value.replace(/[<>:"/\\|?*\x00-\x1f]/g, "-").trim() || "思维导图"; }

ui.sendButton.addEventListener("click", send); ui.chatInput.addEventListener("keydown", (event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); send(); } }); document.querySelectorAll(".quick-prompts button").forEach((button) => button.addEventListener("click", () => { ui.chatInput.value = button.textContent; send(); }));
ui.nodesLayer.addEventListener("click", (event) => { const element = event.target.closest(".map-node"); if (!element) return; const id = element.dataset.id; const tool = event.target.closest("[data-tool]")?.dataset.tool; if (!tool) { state.selectedId = state.selectedId === id ? null : id; render(); return; } const selected = findNode(id); state.selectedId = id; if (tool === "add") { commit(addChildren(selected, ["待补充"])); return; } if (tool === "delete") { const next = clone(state.root); removeFromTree(next, id); commit(next); return; } if (tool === "rename") { const title = prompt("节点名称", selected.title)?.trim(); if (!title) return; const next = clone(state.root); walk(next, (item) => { if (item.id === id) item.title = title; }); commit(next); return; } if (tool === "color") { const next = clone(state.root); walk(next, (item) => { if (item.id === id) item.color = palettes[(palettes.indexOf(item.color) + 1) % palettes.length]; }); commit(next); } });
ui.nodesLayer.addEventListener("dblclick", (event) => { const element = event.target.closest(".map-node"); if (element) element.querySelector('[data-tool="rename"]')?.click(); });
ui.outlineList.addEventListener("click", (event) => { const button = event.target.closest(".outline-item"); if (!button) return; state.selectedId = button.dataset.id; render(); }); ui.outlineList.addEventListener("dblclick", (event) => { const button = event.target.closest(".outline-item"); if (!button) return; const selected = findNode(button.dataset.id); const title = prompt("节点名称", selected.title)?.trim(); if (!title) return; const next = clone(state.root); walk(next, (item) => { if (item.id === selected.id) item.title = title; }); commit(next); });
ui.documentTitle.addEventListener("change", () => { const next = clone(state.root); next.title = ui.documentTitle.value.trim() || "未命名脑图"; commit(next); }); ui.undoButton.addEventListener("click", () => { const previous = state.history.pop(); if (!previous) return; state.future.unshift(clone(state.root)); state.root = previous; render(); save(); }); ui.redoButton.addEventListener("click", () => { const next = state.future.shift(); if (!next) return; state.history.push(clone(state.root)); state.root = next; render(); save(); }); ui.selectionChip.querySelector("button").addEventListener("click", () => { state.selectedId = null; render(); });
document.getElementById("autoLayout").addEventListener("click", () => { render(); centerMap(); showToast("脑图已自动整理"); }); document.querySelectorAll(".structure-picker [data-layout]").forEach((button) => button.addEventListener("click", () => setLayout(button.dataset.layout))); document.querySelectorAll("[data-view]").forEach((button) => button.addEventListener("click", () => { state.view = button.dataset.view; render(); }));
ui.presentPrev.addEventListener("click", () => { state.presentIndex = Math.max(0, state.presentIndex - 1); renderPresentation(); }); ui.presentNext.addEventListener("click", () => { state.presentIndex = Math.min(state.root.children.length - 1, state.presentIndex + 1); renderPresentation(); });
document.getElementById("settingsButton").addEventListener("click", () => { ui.settingsBackdrop.hidden = false; }); ui.modeButton.addEventListener("click", () => { ui.settingsBackdrop.hidden = false; }); document.querySelectorAll(".close-settings").forEach((button) => button.addEventListener("click", () => { ui.settingsBackdrop.hidden = true; })); document.querySelectorAll(".theme-options button").forEach((button) => button.addEventListener("click", () => { state.theme = button.dataset.theme; document.querySelectorAll(".theme-options button").forEach((item) => item.classList.toggle("active", item === button)); save(); render(); }));
function selectProvider(provider) { state.provider = provider; const defaults = providerDefaults[provider]; state.endpoint = defaults.endpoint; state.model = defaults.model; state.apiKey = ""; document.querySelectorAll("[data-provider]").forEach((button) => button.classList.toggle("active", button.dataset.provider === provider)); ui.modelFields.hidden = provider === "demo"; ui.modelEndpoint.value = state.endpoint; ui.modelName.value = state.model; ui.modelKey.value = ""; ui.modeButton.querySelector("b").textContent = provider === "demo" ? "演示模式" : document.querySelector(`[data-provider="${provider}"]`).childNodes[0].textContent; ui.modelNote.textContent = provider === "demo" ? "✓ 无需密钥，可完整体验对话修改流程。" : "地址和模型保存在本机；密钥不落盘，刷新或切换服务即清空。本机模型需允许浏览器跨域访问。"; saveModel(); }
document.querySelectorAll("[data-provider]").forEach((button) => button.addEventListener("click", () => selectProvider(button.dataset.provider))); [ui.modelEndpoint, ui.modelName, ui.modelKey].forEach((input) => input.addEventListener("change", () => { state.endpoint = ui.modelEndpoint.value.trim(); state.model = ui.modelName.value.trim(); state.apiKey = ui.modelKey.value; saveModel(); })); document.getElementById("testModel").addEventListener("click", async () => { state.endpoint = ui.modelEndpoint.value.trim(); state.model = ui.modelName.value.trim(); state.apiKey = ui.modelKey.value; saveModel(); const button = document.getElementById("testModel"); button.disabled = true; ui.modelNote.textContent = "正在连接模型…"; try { const result = await askCompatibleModel("仅回复连接成功，不修改脑图"); ui.modelNote.textContent = `✓ ${result}`; } catch (error) { ui.modelNote.textContent = error.message; } finally { button.disabled = false; } });
document.getElementById("exportButton").addEventListener("click", () => { ui.exportBackdrop.hidden = false; }); document.querySelector(".close-export").addEventListener("click", () => { ui.exportBackdrop.hidden = true; }); document.querySelectorAll("[data-export]").forEach((button) => button.addEventListener("click", async () => { const format = button.dataset.export; const name = safeName(state.root.title); ui.exportBackdrop.hidden = true; button.disabled = true; try { if (format === "markdown") download(`${name}.md`, `# ${state.root.title}\n\n${markdown()}`, "text/markdown;charset=utf-8"); else if (format === "xmind") download(`${name}.xmind`, xmindArchive()); else { const canvas = exportCanvas(); if (format === "png") download(`${name}.png`, await canvasBlob(canvas, "image/png")); else download(`${name}.pdf`, pdfFromCanvas(canvas)); } showToast(`${button.querySelector("b").textContent} 已下载`); } catch (error) { console.error(error); showToast("导出失败，请重试"); } finally { button.disabled = false; } }));
document.getElementById("zoomOut").addEventListener("click", () => { state.scale = Math.max(.5, state.scale - .1); render(); }); document.getElementById("zoomIn").addEventListener("click", () => { state.scale = Math.min(1.4, state.scale + .1); render(); }); function centerMap() { const rootX = Number(ui.mapStage.dataset.rootX || 650); const rootY = Number(ui.mapStage.dataset.rootY || 390); ui.canvasViewport.scrollLeft = Math.max(0, (rootX + 85) * state.scale - ui.canvasViewport.clientWidth / 2); ui.canvasViewport.scrollTop = Math.max(0, (rootY + 29) * state.scale - ui.canvasViewport.clientHeight / 2); } document.getElementById("centerMap").addEventListener("click", centerMap); document.querySelectorAll("[data-mobile-view]").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll("[data-mobile-view]").forEach((item) => item.classList.toggle("active", item === button)); document.querySelector(".workspace").className = `workspace mobile-${button.dataset.mobileView}`; if (button.dataset.mobileView === "map") setTimeout(centerMap); }));
function isValidRoot(root) { if (root?.id !== "root") return false; const ids = new Set(); const valid = (item) => { if (!item || typeof item !== "object" || typeof item.id !== "string" || !item.id || ids.has(item.id) || typeof item.title !== "string" || !Array.isArray(item.children) || (item.color != null && typeof item.color !== "string")) return false; ids.add(item.id); return item.children.every(valid); }; return valid(root); }
try { const stored = JSON.parse(localStorage.getItem(STORAGE_KEY) || "null"); if (stored && isValidRoot(stored.root)) { state.root = stored.root; if (["azure", "teal", "coral"].includes(stored.theme)) state.theme = stored.theme; if (layoutLabels[stored.layout]) state.layout = stored.layout; } else if (stored) localStorage.removeItem(STORAGE_KEY); } catch { localStorage.removeItem(STORAGE_KEY); }
try { const stored = JSON.parse(localStorage.getItem(MODEL_KEY) || "null"); if (stored && providerDefaults[stored.provider]) { Object.assign(state, { provider: stored.provider, endpoint: typeof stored.endpoint === "string" ? stored.endpoint : "", model: typeof stored.model === "string" ? stored.model : "", apiKey: "" }); } } catch { localStorage.removeItem(MODEL_KEY); }
render(); const restoredProvider = state.provider; const restoredEndpoint = state.endpoint; const restoredModel = state.model; selectProvider(restoredProvider); if (restoredProvider !== "demo") { state.endpoint = restoredEndpoint || providerDefaults[restoredProvider].endpoint; state.model = restoredModel || providerDefaults[restoredProvider].model; ui.modelEndpoint.value = state.endpoint; ui.modelName.value = state.model; saveModel(); } requestAnimationFrame(centerMap);
