export const artAssets = [
  { id: 'backdrop', src: './assets/art/backdrop.svg' },
  { id: 'floor-a', src: './assets/art/floor-a.svg' },
  { id: 'floor-b', src: './assets/art/floor-b.svg' },
  { id: 'wall', src: './assets/art/wall.svg' },
  { id: 'crate', src: './assets/art/crate.svg' },
  { id: 'crate-shadow', src: './assets/art/crate-shadow.svg' },
  { id: 'player', src: './assets/art/player.svg' },
  { id: 'goal', src: './assets/art/goal.svg' },
  { id: 'switch-off', src: './assets/art/switch-off.svg' },
  { id: 'switch-on', src: './assets/art/switch-on.svg' },
  { id: 'door-closed', src: './assets/art/door-closed.svg' },
  { id: 'door-open', src: './assets/art/door-open.svg' },
  { id: 'spark', src: './assets/art/spark.svg' },
  { id: 'rail-top', src: './assets/art/rail-top.svg' },
  { id: 'corner-glow', src: './assets/art/corner-glow.svg' },
  { id: 'mist', src: './assets/art/mist.svg' },
  { id: 'clear-burst', src: './assets/art/clear-burst.svg' },
  { id: 'confetti', src: './assets/art/confetti.svg' },
  { id: 'icon-moves', src: './assets/art/icon-moves.svg' },
  { id: 'icon-undo', src: './assets/art/icon-undo.svg' },
  { id: 'icon-reset', src: './assets/art/icon-reset.svg' },
  { id: 'icon-hint', src: './assets/art/icon-hint.svg' },
  { id: 'icon-fullscreen', src: './assets/art/icon-fullscreen.svg' }
];
