import {weightShares,rewardMetrics,generatePool,awardPool,seededRandom,validateProgress,recordAttempt} from './core.mjs?v=20260927-2';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='game-design-fieldnotes-v1',cache=new Map();let catalog=[],progress={schemaVersion:1,lessons:{}},storageOK=true,current=null,renderID=0,noticeTimer,searchID=0;
function notify(s){$('#notice').textContent=s;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').textContent='',4000);}
try{const raw=localStorage.getItem(KEY);if(raw)progress=validateProgress(JSON.parse(raw));}catch{storageOK=false;}
function save(){if(!storageOK){notify('学习记录暂未保存，请先导出当前记录。');return;}try{localStorage.setItem(KEY,JSON.stringify(progress));}catch{storageOK=false;notify('浏览器存储不可用，请导出记录。');}}
function patchRecord(id,patch){progress.lessons[id]={...progress.lessons[id],...patch};save();}
async function load(id){if(cache.has(id))return cache.get(id);const res=await fetch(`data/${id}.json`);if(!res.ok)throw Error('课程暂时未能加载，请稍后重试。');const data=await res.json();cache.set(id,data);return data;}
function route(){return new URLSearchParams(location.hash.slice(1));}
function lessonLink(id,section=''){return `#lesson=${id}${section?'&section='+encodeURIComponent(section):''}`;}
function textOnly(html){const el=document.createElement('div');el.innerHTML=html;return el.textContent;}
function sidebar(results=catalog){const selected=route().get('lesson');let group=0;$('#course-list').innerHTML=results.map(l=>{let h='';if(group!==l.module){group=l.module;h=`<h3 class="unit-title">${String(group).padStart(2,'0')} / ${esc(l.module_title)}</h3>`;}return h+`<a class="course-link ${l.id===selected?'active':''}" href="${lessonLink(l.id)}" ${l.id===selected?'aria-current="page"':''}><span class="num">${l.id.slice(1)}</span><span>${esc(l.title)}</span>${!l.ready?'<span class="pending">待编写</span>':progress.lessons[l.id]?.read?'<span class="pending">已读</span>':''}</a>`;}).join('');}
async function search(){const n=++searchID,q=$('#search').value.trim();if(!q){sidebar();$('#search-status').textContent='';return;}$('#search-status').textContent='搜索中…';const matches=[];for(const l of catalog){let text=l.title+' '+l.question+' '+l.module_title;if(l.ready){const d=await load(l.id);text+=' '+d.sections.map(s=>s.title+' '+textOnly(s.html)).join(' ')+' '+JSON.stringify(d.map);}if(text.toLowerCase().includes(q.toLowerCase()))matches.push(l);}if(n!==searchID)return;sidebar(matches);$('#search-status').textContent=`找到${matches.length}课，点击目录阅读`;}
function home(){current=null;$('#toc').innerHTML='<p class="toc-label">学习的路径</p>'+[...new Set(catalog.map(l=>l.module))].map(n=>`<a href="#module=${n}">${String(n).padStart(2,'0')} ${esc(catalog.find(l=>l.module===n).module_title)}</a>`).join('');const last=catalog.find(l=>l.id===progress.lastLesson&&l.ready);const next=last||catalog[0];$('#content').innerHTML=`<div class="hero"><span class="eyebrow">GAME DESIGN · THEORY & PRACTICE</span><h1>让规则有道理，<br>让体验有回响。</h1><p class="lead">从一次选择开始，理解玩家、随机奖励与交易世界。</p><p>50课组成一条连续的设计路径。观察一个现象，拆开它的条件，算清一个例子，再把结论放回游戏里。</p><div class="meta"><span class="chip">${catalog.filter(l=>l.ready).length}课可阅读</span><span class="chip">10个单元</span><span class="chip">图文 · 全文讲解 · 设计实践</span></div><div class="actions"><a class="solid" href="${lessonLink(next.id)}">${last?'继续阅读':'开始阅读'} → ${esc(next.title)}</a><a href="#lab=weights">进入交互实验室</a><a href="https://rpv4d9p6q2.feishu.cn/docx/IIC3dnj2bo2Zz3xQD5hc2WfVnCd" target="_blank" rel="noopener">飞书教材目录 ↗</a></div></div>`+Array.from({length:10},(_,i)=>`<section class="module" id="module-${i+1}"><span class="eyebrow">UNIT ${String(i+1).padStart(2,'0')}</span><h2>${esc(catalog.find(l=>l.module===i+1)?.module_title||'')}</h2><div class="cards">${catalog.filter(l=>l.module===i+1).map(l=>`<a class="card ${l.ready?'':'planned'}" href="${lessonLink(l.id)}"><div class="card-meta"><span>${l.id} / 120分钟</span><span>${l.ready?'可阅读':'正文待编写'}</span></div><h3>${esc(l.title)}</h3><p>${esc(l.question)}</p></a>`).join('')}</div></section>`).join('');}
function video(v){return `<div class="video-box"><div class="video-title">${esc(v.title)}<small>${esc(v.author)} · P${v.page} · ${Math.floor(v.duration/60)}:${String(v.duration%60).padStart(2,'0')} · ${esc(v.verified)}</small></div><iframe title="${esc(v.title)} · 第${v.page}集" loading="lazy" allow="fullscreen" allowfullscreen src="https://player.bilibili.com/player.html?bvid=${v.bvid}&page=${v.page}&p=${v.page}&autoplay=0"></iframe><div class="video-caption">若内嵌受限，可<a href="${esc(v.url)}" target="_blank" rel="noopener noreferrer">到B站观看本分集 ↗</a>。全课主看与暂停记录共25分钟；本片观看范围见本节说明。</div></div>`;}
function mapHTML(d){return `<section class="lesson-section" id="mindmap"><h2>知识地图</h2><p class="muted">每条分支概括一个要点。展开主题查看细节，点击“阅读本节”回到完整推导。</p><div class="map-tools"><button id="expand-map">展开全部</button><button id="collapse-map">收起全部</button><button id="zoom-map" aria-label="放大脑图文字">字号＋</button></div><div class="map-root">${esc(d.title)}<small>${Object.keys(d.map).length}个主题 · ${Object.values(d.map).flat().length}个要点</small></div><div class="map-grid">${Object.entries(d.map).map(([title,nodes])=>`<details><summary>${esc(title)} <small>· ${nodes.length}</small></summary><a class="map-read" href="${lessonLink(d.id,d.map_links[title])}">阅读本节 ↗</a><ul>${nodes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul></details>`).join('')}</div></section>`;}
function audioHTML(d){return `<section class="lesson-section" id="audio"><h2>全文讲解</h2><div class="audio-panel"><span class="eyebrow">LISTEN & THINK</span><p class="muted">${d.audio.duration} · 自然普通话合成讲解 · 阅读与同内容音频可替代</p><audio controls preload="none" src="${d.audio.src}"><track kind="captions" src="${d.audio.subtitles}" srclang="zh" label="中文讲稿"></audio><div class="audio-controls"><label>语速 <select id="speed"><option value=".8">0.8×</option><option value="1" selected>1×</option><option value="1.2">1.2×</option><option value="1.5">1.5×</option></select></label><button id="transcript-button">展开全文讲稿</button><a href="${d.audio.subtitles}" download>字幕</a></div><p id="audio-caption" class="muted" aria-live="off"></p><div id="transcript" class="transcript" hidden></div></div></section>`;}
function quizHTML(d){return `<section class="lesson-section" id="quiz"><h2>理解与应用</h2><p class="muted">先独立作答，再查看解析。每题25分，分数只对应本课四题。</p><form id="quiz-form">${d.quiz.map((q,i)=>`<fieldset><legend>${i+1}. ${esc(q.stem)}</legend>${q.options.map((x,j)=>`<label><input type="radio" name="q${i}" value="${j}" required>${String.fromCharCode(65+j)}. ${esc(x)}</label>`).join('')}<div id="answer-${i}"></div></fieldset>`).join('')}<button class="primary" type="submit">检查答案</button> <button type="reset">重新作答</button><div id="score" class="score" role="status"></div></form><p><a href="${d.form}" target="_blank" rel="noopener">也可使用飞书测验 ↗</a></p></section>`;}
async function renderLesson(l,n){current=null;$('#content').innerHTML='<p class="loading">正在打开课程…</p>';if(!l.ready){current=l.id;$('#toc').innerHTML='';$('#content').innerHTML=`<div class="lesson-heading"><span class="eyebrow">${l.id} / ${esc(l.module_title)}</span><h1>${esc(l.title)}</h1><p class="question">${esc(l.question)}</p></div><p class="schedule"><b>正文正在编写</b>本课尚未具备完整教材、音频与练习，不计入已发布课程。</p><h2>预期实践</h2><p>${esc(l.practice)}</p><h2>相关先修</h2><div class="actions">${l.prerequisites.map(id=>`<a href="${lessonLink(id)}">${id} ${esc(catalog.find(x=>x.id===id)?.title||'')}</a>`).join('')}</div><p><a href="#">返回课程目录</a></p>`;return;}
 const d=await load(l.id);if(n!==renderID)return;current=l.id;progress.lastLesson=l.id;save();let vi=0;const visible=d.sections.filter(s=>!/^练习|^解答|^选择题/.test(s.title));
 $('#content').innerHTML=`<div class="lesson-heading"><span class="eyebrow">UNIT ${String(l.module).padStart(2,'0')} · ${esc(l.module_title)} / ${l.id}</span><h1>${esc(l.title)}</h1><p class="question">${esc(l.question)}</p><div class="meta"><span class="chip">120分钟</span><span class="chip">全文讲解 ${d.audio.duration}</span><span class="chip">${Object.values(d.map).flat().length}个脑图要点</span></div><div class="actions"><a href="${l.url}" target="_blank" rel="noopener">打开飞书原课 ↗</a><a href="#lesson=${l.id}&section=quiz">前往练习</a></div></div><div class="schedule"><b>本课安排</b>导读10 · 视频与观察25 · 图文或音频与推导35 · 实践20 · 练习订正25 · 总结5分钟</div>`;
 const overview=visible.shift();if(overview)$('#content').insertAdjacentHTML('beforeend',`<section class="lesson-section" id="${overview.id}"><h2>${esc(overview.title)}</h2>${overview.html}</section>`);
 $('#content').insertAdjacentHTML('beforeend',mapHTML(d)+audioHTML(d));

 for(let i=0;i<visible.length;i++){const s=visible[i];let extra='';if(/视频/.test(s.title)&&vi<d.videos.length)extra+=video(d.videos[vi++]);for(const f of d.figures.filter(f=>f.section===s.id)){extra+=`<figure class="figure"><img src="${f.src}" alt="${esc(f.alt)}" width="${f.width}" height="${f.height}" loading="lazy"><figcaption>${esc(f.alt)} · 教学图解</figcaption></figure>`;}$('#content').insertAdjacentHTML('beforeend',`<section class="lesson-section" id="${s.id}" data-legacy-id="${s.legacy_id}"><h2>${esc(s.title)}</h2>${s.html}${extra}</section>`);}
 if(vi<d.videos.length)$('#content').insertAdjacentHTML('beforeend',`<section class="lesson-section" id="videos"><h2>视频观察</h2>${d.videos.slice(vi).map(video).join('')}</section>`);
 $('#content').insertAdjacentHTML('beforeend',quizHTML(d)+`<section class="lesson-section" id="notes"><h2>思考与设计笔记</h2><p>${esc(l.practice)}</p><div class="note-state"><label><input id="read-state" type="checkbox" ${progress.lessons[l.id]?.read?'checked':''}> 我已读完本课</label><label><input id="review-state" type="checkbox" ${progress.lessons[l.id]?.review?'checked':''}> 需要复习</label></div><label for="note">写下结论、成立条件，以及一个可能推翻它的例子。</label><textarea id="note" class="note-area" maxlength="50000" placeholder="我的设计问题是……">${esc(progress.lessons[l.id]?.note||'')}</textarea><p class="muted">仅保存在本浏览器。发布状态、观看勾选与理解程度分别记录。</p></section><nav class="chapter-footer" aria-label="前后课程">${l.number>1?`<a href="${lessonLink(catalog[l.number-2].id)}">← ${esc(catalog[l.number-2].title)}</a>`:'<a href="#">← 课程目录</a>'}${l.number<50?`<a href="${lessonLink(catalog[l.number].id)}">${esc(catalog[l.number].title)} →</a>`:''}</nav>`);
 document.querySelectorAll('.lesson-section table').forEach(table=>{const w=document.createElement('div');w.className='table-wrap';table.replaceWith(w);w.append(table);});
 $('#toc').innerHTML='<p class="toc-label">本课索引</p>'+[...document.querySelectorAll('.lesson-section')].map(s=>`<a href="${lessonLink(l.id,s.id)}">${esc(s.querySelector('h2').textContent)}</a>`).join('');
 $('#expand-map').onclick=()=>document.querySelectorAll('.map-grid details').forEach(e=>e.open=true);$('#collapse-map').onclick=()=>document.querySelectorAll('.map-grid details').forEach(e=>e.open=false);let size=14;$('#zoom-map').onclick=()=>{$('.map-grid').style.fontSize=(size=size>=20?14:size+2)+'px';};
 const player=$('audio');$('#speed').onchange=e=>player.playbackRate=Number(e.target.value);player.addEventListener('error',()=>notify('音频暂时无法加载，请重试或打开飞书原课。'));
 $('#transcript-button').onclick=async()=>{const box=$('#transcript'),button=$('#transcript-button');try{if(box.hidden&&!box.textContent){const res=await fetch(d.audio.transcript);if(!res.ok)throw Error('讲稿加载失败');const text=await res.text();if(!box.isConnected)return;box.textContent=text;}if(!box.isConnected)return;box.hidden=!box.hidden;button.textContent=box.hidden?'展开全文讲稿':'收起讲稿';}catch{if(box.isConnected)notify('讲稿暂时无法加载，请重试。');}};
 const track=player.textTracks[0];if(track){track.mode='hidden';track.oncuechange=()=>$('#audio-caption').textContent=[...track.activeCues||[]].map(c=>c.text).join(' ');}

 $('#quiz-form').onsubmit=e=>{e.preventDefault();const form=new FormData(e.currentTarget),answers=d.quiz.map((_,i)=>Number(form.get('q'+i)));progress=recordAttempt(progress,l.id,answers,d.quiz.map(q=>q.answer),new Date().toISOString());save();d.quiz.forEach((q,i)=>$('#answer-'+i).innerHTML=`<div class="answer ${answers[i]!==q.answer?'wrong':''}">${answers[i]===q.answer?'答对了':'需要订正'} · 正确选项${String.fromCharCode(65+q.answer)}<br>${esc(q.why)}</div>`);const r=progress.lessons[l.id];$('#score').textContent=`本次 ${r.latest.score}分 · 首次 ${r.first.score}分`;};
 $('#quiz-form').onreset=()=>{d.quiz.forEach((_,i)=>$('#answer-'+i).textContent='');$('#score').textContent='';};
 $('#note').oninput=e=>patchRecord(l.id,{note:e.target.value});$('#read-state').onchange=e=>{patchRecord(l.id,{read:e.target.checked});sidebar();};$('#review-state').onchange=e=>patchRecord(l.id,{review:e.target.checked});
 if(progress.lessons[l.id]?.latest)$('#score').textContent=`上次 ${progress.lessons[l.id].latest.score}分 · 首次 ${progress.lessons[l.id].first.score}分`;
}
const percent=x=>(x*100).toFixed(2)+'%',num=x=>Number(x.toFixed(4)).toLocaleString('zh-CN');
function lab(kind){current=null;$('#toc').innerHTML='';const types={weights:'权重与分母',pool:'七槽与七选一',reward:'返还与波动'};if(!(kind in types))kind='weights';$('#content').innerHTML=`<div class="lesson-heading"><span class="eyebrow">DESIGN LAB / 可复算的实验</span><h1>${types[kind]}</h1><p class="question">改一个参数，观察它改变了什么，又没有改变什么。</p></div><nav class="lab-tabs">${Object.entries(types).map(([k,v])=>`<a href="#lab=${k}" ${k===kind?'aria-current="page"':''}>${v}</a>`).join('')}</nav><div id="lab-body"></div>`;
 if(kind==='weights'){$('#lab-body').innerHTML='<p>三件物品均符合当前人群和品质条件。概率等于自身权重除以候选总权重。</p><div class="lab-inputs">'+[4,2,2].map((v,i)=>`<label>物品${'ABC'[i]}权重<input type="number" min="0" value="${v}" id="w${i}"></label>`).join('')+'</div><div id="lab-result" aria-live="polite"></div><p class="schedule">试试把A从4改成8。自身权重翻倍，分母也从8变成12，所以概率从50%变为66.67%。</p>';const update=()=>{try{const w=[0,1,2].map(i=>$('#w'+i).value.trim()===''?NaN:Number($('#w'+i).value)),ps=weightShares(w);$('#lab-result').innerHTML='<div class="bar-track">'+ps.map(p=>`<span style="width:${p*100}%"></span>`).join('')+'</div><div class="metric-grid">'+ps.map((p,i)=>`<div class="metric"><span>${'ABC'[i]}：${w[i]} ÷ ${w.reduce((a,b)=>a+b,0)}</span><b>${percent(p)}</b></div>`).join('')+'</div>';}catch(e){$('#lab-result').innerHTML='<p class="error">'+esc(e.message)+'</p>';}};$('.lab-inputs').oninput=update;update();}
 if(kind==='reward'){$('#lab-body').innerHTML='<p>数量采用教学筹码，不把挂件品质换算成金额。概率需要合计100%。</p><div class="lab-inputs"><label>每轮成本<input id="cost" type="number" value="10" min=".01"></label></div><div class="lab-inputs">'+[0,10,30].map((v,i)=>`<div><label>档${i+1}总返还<input type="number" id="amount${i}" value="${v}" min="0"></label><label>概率（%）<input type="number" id="prob${i}" value="${[60,30,10][i]}" min="0" max="100"></label></div>`).join('')+'</div><div id="lab-result" aria-live="polite"></div><p class="schedule">有返还不等于净赚。返还10、成本10时，净收益为零；方差描述波动，不能用期望替代。</p>';const update=()=>{try{const val=id=>$(id).value.trim()===''?NaN:Number($(id).value),rows=[0,1,2].map(i=>({amount:val('#amount'+i),p:val('#prob'+i)/100})),m=rewardMetrics(rows,val('#cost'));$('#lab-result').innerHTML='<div class="metric-grid">'+[['期望总返还',num(m.expected)+'枚'],['期望净收益',num(m.net)+'枚'],['RTP',percent(m.rtp)],['有返还频率',percent(m.returnRate)],['净赚频率',percent(m.profitRate)],['总返还方差',num(m.variance)+'枚²']].map(([k,v])=>`<div class="metric"><span>${k}</span><b>${v}</b></div>`).join('')+'</div><p>'+rows.map(r=>`${r.amount} × ${percent(r.p)}`).join(' + ')+` = ${num(m.expected)}枚</p>`;}catch(e){$('#lab-result').innerHTML='<p class="error">'+esc(e.message)+'</p>';}};$('#lab-body').oninput=update;update();}
 if(kind==='pool'){$('#lab-body').innerHTML='<p>教学目录每种品质10件：只有各品质01号限制G1，02号限制G2，其余共通；03号起权重2，其余权重1。每池ID不重复，最后每个位置均为1/7。</p><div class="lab-inputs"><label>人群<select id="group">'+['G1','G2','G3','G4','G5'].map(g=>`<option>${g}</option>`).join('')+'</select></label><label>品质档位<select id="tier"><option value="0">70 / 22 / 8</option><option value="1">60 / 30 / 10</option><option value="2">50 / 38 / 12</option></select></label><label>随机种子<input id="seed" type="number" value="17" min="0" max="4294967295"></label></div><div class="actions"><button id="generate" class="primary">生成七槽</button><button id="award" disabled>均匀领取一件</button></div><div id="lab-result" aria-live="polite"></div><p class="schedule">这是固定种子的教学演示，不是线上抽奖。生成权重不再次用于领取。候选不足时停止，不偷偷改品质。无保底；领取后品质档位恢复默认。</p>';let pool=[],rng;const items=Array.from({length:30},(_,i)=>({id:['普','稀','传'][Math.floor(i/10)]+String(i%10+1).padStart(2,'0'),quality:Math.floor(i/10),weight:i%10>=2?2:1,blocked:i%10===0?['G1']:i%10===1?['G2']:[]}));const invalidate=()=>{pool=[];$('#award').disabled=true;$('#lab-result').textContent='配置已改变，请重新生成。';};$('.lab-inputs').onchange=invalidate;$('#generate').onclick=()=>{try{const seed=Number($('#seed').value);if(!Number.isInteger(seed)||seed<0||seed>4294967295||!$('#seed').value)throw Error('请输入0至4294967295的整数种子');rng=seededRandom(seed);pool=generatePool(items,[[70,22,8],[60,30,10],[50,38,12]][Number($('#tier').value)],$('#group').value,rng);$('#lab-result').innerHTML='<div class="slots">'+pool.map((x,i)=>`<div class="slot q${x.quality}" id="slot${i}"><small>槽${i+1} · ${['普通','稀有','传说'][x.quality]}</small><b>${x.item.id}</b><small>生成 ${x.item.weight}/${x.denominator}</small><small>领取 1/7</small></div>`).join('')+'</div><p>每一步分母已排除本组禁用和先前入池物品。上方权重比是在对应品质已确定条件下的选择概率。</p><div id="winner"></div>';$('#award').disabled=false;}catch(e){$('#lab-result').innerHTML='<p class="error">'+esc(e.message)+'</p>';$('#award').disabled=true;}};$('#award').onclick=()=>{const winner=awardPool(pool,rng),i=pool.indexOf(winner);$('#slot'+i).classList.add('winner');$('#winner').textContent='本次领取：'+winner.item.id+'。品质档位已恢复70 / 22 / 8。';$('#tier').value='0';$('#award').disabled=true;};}
}
function scrollSection(id){const el=document.getElementById(id)||[...document.querySelectorAll('[data-legacy-id]')].find(e=>e.dataset.legacyId===id);if(el){el.scrollIntoView();if(current)patchRecord(current,{position:el.id});}}
function rememberPosition(){if(!current||!cache.has(current)||route().get('lesson')!==current)return;const sections=[...document.querySelectorAll('.lesson-section')];const visible=sections.filter(e=>e.getBoundingClientRect().top<=innerHeight*.35).at(-1);patchRecord(current,{position:visible?.id||'overview'});}
window.addEventListener('pagehide',rememberPosition);
let positionTimer;window.addEventListener('scroll',()=>{clearTimeout(positionTimer);positionTimer=setTimeout(rememberPosition,250);},{passive:true});
async function render(){clearTimeout(positionTimer);const n=++renderID,params=route(),id=params.get('lesson');if(current===id&&params.has('section')){scrollSection(params.get('section'));return;}document.querySelectorAll('audio,video').forEach(x=>x.pause());document.body.classList.remove('menu-open');$('#menu').setAttribute('aria-expanded','false');sidebar();if($('#search').value.trim())search().catch(e=>notify(e.message));try{if(id){const l=catalog.find(x=>x.id===id);if(!l)throw Error('没有这个课次，请从课程目录选择。');await renderLesson(l,n);}else if(params.has('lab'))lab(params.get('lab'));else home();if(n!==renderID)return;document.title=(id?catalog.find(x=>x.id===id).title+' · ':'')+'游戏设计研习册';if(params.has('section'))scrollSection(params.get('section'));else if(params.has('module'))document.getElementById('module-'+params.get('module'))?.scrollIntoView();else if(id&&progress.lessons[id]?.position)scrollSection(progress.lessons[id].position);else window.scrollTo(0,0);}catch(e){if(n!==renderID)return;$('#content').innerHTML=`<p class="error">${esc(e.message)}</p><a href="#">返回目录</a>`;}}
$('.skip').onclick=e=>{e.preventDefault();$('#content').focus();$('#content').scrollIntoView();};
$('#search').oninput=()=>search().catch(e=>$('#search-status').textContent=e.message);$('#menu').onclick=()=>{document.body.classList.toggle('menu-open');$('#menu').setAttribute('aria-expanded',document.body.classList.contains('menu-open'));};
$('#records').onclick=()=>{$('#storage-message').textContent=storageOK?'记录自动保存在当前浏览器。':'原存储不可读取或不可写。不会覆盖原数据；请导出本次记录。';$('#record-dialog').showModal();};
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(progress,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='游戏设计-学习记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>3e6)throw Error('记录文件超过3MB');const next=validateProgress(JSON.parse(await f.text()));$('#import-preview').innerHTML=`<p>识别到${Object.keys(next.lessons).length}课记录。同课导入项将覆盖对应字段，其他课程保留。</p><button id="confirm-import">确认合并</button>`;$('#confirm-import').onclick=()=>{const merged=validateProgress(progress);if(next.lastLesson)merged.lastLesson=next.lastLesson;for(const [id,row]of Object.entries(next.lessons))merged.lessons[id]={...merged.lessons[id],...row};progress=merged;save();$('#import-preview').textContent='已合并到当前学习记录。';current=null;render();notify(storageOK?'记录已保存':'已合并，存储不可用，请导出备份');};}catch(err){$('#import-preview').textContent='未导入：'+err.message;}};
window.addEventListener('hashchange',render);window.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('menu-open');$('#menu').setAttribute('aria-expanded','false');}});
try{const res=await fetch('data/catalog.json');if(!res.ok)throw Error('目录加载失败');catalog=await res.json();await render();}catch(e){$('#content').textContent=e.message;}
