for(const href of ['announcement.css','reference.css','exchange.css','gameplay.css','results.css']){const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.append(link);}
const $=s=>document.querySelector(s);const STORE='holiday-prototype-v37';
const dates=Array.from({length:13},(_,i)=>new Date(Date.UTC(2026,8,25+i)).toISOString().slice(0,10));
const names=['兔灯挂件','桂花香囊','月兔团圆','团圆茶杯','秋游挎包','出游墨镜','假日出游','野餐水壶','随行相机','秋日花束','假日行李箱','枫叶挂饰','枫叶漫游'];const skins=[2,6,12];
const prices=[4,4,18,4,10,4,20,4,4,10,24,4,22];
const qualities=['普通','普通','皮肤','普通','稀有','普通','皮肤','普通','普通','稀有','传说','普通','皮肤'];
function quantity(i){return Number(state.quantities[i]||0)}
function challengeUsed(){return state.playedDays.includes(day())}
function canStart(){return phase()==='open'&&(Boolean(state.game)||!challengeUsed())}
function moonCost(n){return `<span class="moon-cost"><img src="assets/exchange/block_shouji.png" alt="月饼"><b>×${n}</b></span>`;}
const fresh=()=>({date:'2026-09-25T12:00:00',total:0,claimed:[],quantities:{},playedDays:[],seen:[],tutorial:false,game:null,attempts:0});let state;try{state=JSON.parse(localStorage.getItem(STORE))||fresh()}catch{state=fresh()}let page='home',selected=null,lock=false,dialog=null,toastTimer,dragStart=null,blockClick=false;
function save(){localStorage.setItem(STORE,JSON.stringify(state))}function day(){return state.date.slice(0,10)}function phase(){return day()<'2026-09-24'||day()>='2026-10-12'?'hidden':day()<'2026-09-25'?'preview':day()>='2026-10-08'?'ended':'open'}function fmt(d){return +d.slice(5,7)+'月'+ +d.slice(8,10)+'日'}function canClaim(i){return Number.isInteger(i)&&i>=0&&i<13&&phase()==='open'&&day()>=dates[i]&&state.total>=prices[i]&&(!skins.includes(i)||!quantity(i))}
function leftTime(){let target=phase()==='preview'?'2026-09-25T00:00:00':'2026-10-08T00:00:00',mins=Math.max(0,Math.floor((new Date(target)-new Date(state.date))/60000));return phase()==='ended'?'活动已结束':phase()==='preview'?`距开启${Math.floor(mins/60)}时${String(mins%60).padStart(2,'0')}分`:mins<1440?`剩余${Math.floor(mins/60)}时${String(mins%60).padStart(2,'0')}分`:`剩余${Math.ceil(mins/1440)}天`}
function art(i){const file={2:'moon',6:'travel',12:'autumn'}[i];if(file)return `<img class="art skin-art" src="assets/exchange/skin-${file}.png" alt="${names[i]}限定砖块皮肤">`;const icon={3:'cup',5:'sunglasses',7:'bottle',9:'bouquet',11:'maple'}[i];if(icon)return `<img class="art accessory-art" src="assets/rewards/${icon}.png" alt="${names[i]}">`;let old={0:0,1:1,4:3,8:5,10:6}[i],col=old%2,row=Math.floor(old/2);return `<div class="art" style="background-size:800px 1422px;background-position:${col?-417:-99}px ${-551-row*174}px" role="img" aria-label="${names[i]}"></div>`}
function toast(t){if(page==='game')return;clearTimeout(toastTimer);$('#toast').textContent=t;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function resize(){let mobile=innerWidth<=760;let scale=mobile?Math.min(innerWidth/750,(innerHeight-6)/1624):Math.min((innerHeight-48)/1624,(innerWidth-390)/750,1);scale=Math.max(.15,scale);$('#phone').style.transform=`scale(${scale})`;$('#phone-wrap').style.width=750*scale+'px';$('#phone-wrap').style.height=1624*scale+'px'}addEventListener('resize',resize);
function navigate(next){if(next==='activity'&&phase()==='hidden')next='home';clearTimeout(toastTimer);$('#toast').classList.remove('show');closeModal();page=next;selected=null;render();$('#screen').classList.remove('enter');void $('#screen').offsetWidth;$('#screen').classList.add('enter')}
let exchangeScroll=0;
function render(){const priorList=$('.exchange-list');if(priorList)exchangeScroll=priorList.scrollTop;let h='';if(page==='home')h=`<div class="page home">${phase()!=='hidden'?`<button class="hot entry" data-action="activity" aria-label="好事成双活动入口">${dates.some((_,i)=>canClaim(i))?'<i class="red-dot"></i>':''}</button><div class="entry-time">${leftTime()}</div>`:'<div style="position:absolute;left:620px;top:681px;width:130px;height:170px;background:#43b783"></div>'}<button class="hot" style="left:16px;top:345px;width:125px;height:118px" data-action="gallery" aria-label="我的名片"></button><button class="hot" style="left:170px;top:1320px;width:410px;height:134px" data-action="daily" aria-label="加入牌局"></button><button class="hot" style="left:33px;top:170px;width:78px;height:75px" data-action="settings" aria-label="设置"></button></div>`;
if(page==='activity')h=activityMarkup();
if(page==='game'){h=`<div class="page game">${sceneMarkup()}<div class="game-date">${fmt(state.game?.date||day())}</div><button class="game-settings" data-action="pause" aria-label="暂停设置"></button><div class="board-area" id="board"></div><button class="stash" data-action="stash">暂存</button><div class="game-tools"><button class="tool" data-action="slot"><span>▣</span>槽位</button><button class="tool" data-action="shuffle"><span>↝</span>洗牌</button><button class="tool" data-action="pair"><span>∩</span>配对</button></div></div>`}
if(page==='success'||page==='failure')h=resultMarkup(page==='success');
$('#screen').innerHTML=h;const nextList=$('.exchange-list');if(nextList){nextList.scrollTop=exchangeScroll;bindRewardDrag(nextList)}if(page==='game')renderBoard();$('#date').value=state.date;$('#stats').textContent=`${state.total} 个月饼 · ${state.claimed.length} / 13 款 · ${Object.values(state.quantities).reduce((a,b)=>a+b,0)} 件`;$('#screenLabel').textContent=({home:'主界面',activity:'活动兑换页',game:'活动关卡',success:'成功结算',failure:'墓碑失败结算'})[page];document.querySelectorAll('#flow li').forEach(el=>el.classList.toggle('active',el.dataset.step===(page==='failure'?'success':page)));save()}
function openModal(body,kind=''){dialog=kind;$('#modal-root').innerHTML=`<div class="shade"><section class="modal ${kind}" role="dialog" aria-modal="true"><button class="close" data-action="close" aria-label="关闭弹窗">×</button>${body}</section></div>`;$('#modal-root .close').focus();$('#screenLabel').textContent=kind==='announcement'?'活动公告':kind==='reward'?'恭喜获得':kind==='tutorial'?'月饼砖首次说明':'弹窗';}
function closeModal(){dialog=null;$('#modal-root').innerHTML=''}
function showAnnouncement(){openModal(`<div class="reference-stage"><img class="reference-art" src="assets/announcement-moon-rabbit.png" alt="好事成双开启啦，月兔睡衣砖块小人。活动时间9月25日到10月7日。">${phase()==='preview'?'<div class="preview-heading">好事成双 · 明日开启</div>':''}<div class="announcement-copy">挑战收集月饼，自由兑换限定外观</div><button class="ref-hot announcement-x" data-action="close" aria-label="关闭公告">关闭</button><button class="ref-hot announcement-next" data-action="activity" aria-label="去看看">去看看</button></div>`,'announcement');}
function login(){navigate('home');if(['2026-09-24','2026-09-25'].includes(day())&&!state.seen.includes(day())){state.seen.push(day());save();showAnnouncement()}}
function preview(i){if(!Number.isInteger(i)||i<0||i>=13)return;openModal(`<h2>${names[i]}</h2><div class="reward-space">${art(i)}</div><p>${skins.includes(i)?'限定砖块皮肤':qualities[i]+'随身小物'}</p><small>${fmt(dates[i])}开启 · 兑换消耗 ${moonCost(prices[i])}</small><p>${skins.includes(i)?quantity(i)?'已放入图鉴':'每款限兑1次':`当前拥有 ${quantity(i)} 件 · 可重复兑换`}</p><button class="white-btn" data-action="${canClaim(i)?'exchange':'close'}" data-id="${i}">${canClaim(i)?'兑换':'知道了'}</button>`)}
function claim(i){if(lock||!canClaim(i))return;lock=true;const requestedDay=day();setTimeout(()=>{if(day()===requestedDay&&canClaim(i)){state.total-=prices[i];state.quantities[i]=quantity(i)+1;if(!state.claimed.includes(i))state.claimed.push(i);save();render();openModal(`<h2>恭喜获得</h2><div class="reward-space">${art(i)}</div><h2>${names[i]}</h2><p>${skins.includes(i)?'砖块皮肤':qualities[i]+'随身小物 · ×1'}</p><small>${skins.includes(i)?'已放入图鉴，尚未穿戴':`已放入图鉴，当前拥有 ${quantity(i)} 件`}</small><p><button class="white-btn" data-action="close">收下</button></p>`,'reward');document.querySelectorAll('#flow li').forEach(el=>el.classList.toggle('active',el.dataset.step==='reward'))}lock=false},260)}
function start(){if(!canStart()){toast(phase()==='open'?'今日挑战已结束，明天再来':'活动尚未开放或已经结束');return}if(!state.game){let tiles=[];for(let pair=0;pair<21;pair++){for(let a=0;a<2;a++)tiles.push({id:pair*2+a,type:pair<6?'moon':(pair-6)%9,hp:3,gone:false})}shuffle(tiles);state.game={tiles,date:day(),count:0,started:Date.now(),stashed:null};state.playedDays.push(day());state.attempts=1;save()}navigate('game');if(!state.tutorial)showMoonTutorial()}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const faces=[[28,334],[130,334],[233,334],[333,334],[438,334],[540,334],[643,334],[28,538],[130,538]];
function renderBoard(){let g=state.game;if(!g)return;$('#board').innerHTML=g.tiles.map((t,i)=>`<button aria-label="${t.type==='moon'?['','剩三分之一月饼','剩三分之二月饼','完整月饼'][t.hp]:'普通砖块'+t.type}" class="tile ${t.gone?'gone':''} ${selected===t.id?'selected':''}" style="left:${i%7*100}px;top:${Math.floor(i/7)*122+22}px;${g.stashed===t.id?'transform:translateY(45px);filter:brightness(.95)':''}" data-tile="${t.id}">${tileFace(t)}</button>`).join('');queueMicrotask(checkBoardOutcome)}
function selectTile(id){if(lock||dialog||!state.game)return;let g=state.game,t=g.tiles.find(x=>x.id===id);if(!t||t.gone)return;if(selected===null||selected===id){selected=selected===id?null:id;renderBoard();return}let a=g.tiles.find(x=>x.id===selected);if(a.type!==t.type||(a.type==='moon'&&a.hp!==t.hp)){selected=id;renderBoard();toast('选择相同图案、相同状态的两块砖');return}match(a,t)}
async function match(a,b){if(lock)return;lock=true;const game=state.game;await animateCollision(a,b);if(game!==state.game){lock=false;return}if(a.type==='moon'&&a.hp>1){a.hp--;b.hp--;}else{a.gone=b.gone=true;if(a.type==='moon')game.count+=2;}selected=null;lock=false;save();if(page==='game'){renderBoard();if(game.tiles.every(x=>x.gone))settle(true)}}
function settle(win,demo=false){if(phase()!=='open'){state.game=null;save();navigate('activity');toast('活动已结束，本次不再新增月饼');return}if(lock)return;let g=state.game;if(!g){if(!demo)return;if(challengeUsed()){toast('今日挑战已结算，请切换到次日');return}g={count:0,date:day(),started:Date.now()};state.playedDays.push(day());state.attempts=1}let count=demo&&win?12:Math.min(12,g.count);let before=dates.map((_,i)=>canClaim(i));state.total+=count;state.result={count,seconds:Math.max(1,Math.floor((Date.now()-g.started)/1000)),date:g.date,newReward:false};state.result.newReward=dates.some((_,i)=>canClaim(i)&&!before[i]);state.game=null;save();navigate(win?'success':'failure')}
function returnActivity(){let r=state.result;navigate('activity');if(phase()==='open'&&r?.count>0)toast(r.newReward?'月饼收好啦，选一份喜欢的好礼吧！':'月饼收好啦，明天继续攒好礼！')}
function pause(){openModal('<h2>休息一下</h2><p>当前挑战进度会保留</p><button class="white-btn" data-action="close">继续挑战</button><button class="white-btn" data-action="save-exit">保存并返回</button><button class="white-btn" data-action="giveup">放弃挑战</button>')}
const actions={home:()=>navigate('home'),activity:()=>navigate('activity'),start,again:start,return:returnActivity,close:()=>{closeModal();render()},preview,claim,exchange:confirmExchange,tutorial:()=>{state.tutorial=true;save();closeModal();render()},pause,'save-exit':()=>navigate('activity'),giveup:()=>openModal('<h2>确定放弃本次挑战？</h2><p>放弃后本局结束<br>已彻底消除的月饼会计入进度</p><button class="white-btn" data-action="close">继续挑战</button><button class="white-btn" data-action="confirm-giveup">确认放弃</button>'),'confirm-giveup':()=>settle(false),rules:()=>openModal('<h2>活动说明</h2><p>9月25日—10月7日<br>挑战活动关卡，收集月饼。</p><p>8档任务按日期依次开启。<br>达到累计目标后，点击领取好礼。<br>领取奖励不扣除已收集的月饼。</p><p>月饼砖碰三次才会消除。<br>成功、失败或确认放弃时，<br>已消除的月饼均计入活动进度。</p><small>活动结束前记得完成结算、领取奖励。<br>已获得的皮肤和随身小物永久保留。</small><p><button class="white-btn" data-action="close">知道了</button></p>'),gallery:()=>openModal(`<h2>我的外观</h2>${state.claimed.length?`<div class="gallery-items">${state.claimed.map(i=>`<div class="gallery-item">${art(i)}${names[i]}</div>`).join('')}</div>`:'<p>还没有获得活动外观<br>去好事成双收集第一份好礼吧</p>'}<button class="white-btn" data-action="activity">前往活动</button>`),daily:()=>openModal('<h2>每日挑战</h2><p>本体验版展示双节活动流程。<br>从主界面“好事成双”入口<br>进入活动挑战。</p><button class="white-btn" data-action="activity">去好事成双</button>'),settings:()=>openModal('<h2>设置</h2><p>当前体验进度保存在本机。<br>可通过演示面板模拟重开游戏。</p><button class="white-btn" data-action="close">返回</button>'),share:()=>openModal('<h2>晒晒今天的月饼</h2><p>挑战成功，假日好礼又近一步！</p><small>分享效果预览，体验版不向好友发送消息</small><p><button class="white-btn" data-action="close">返回结算</button></p>'),shuffle:()=>{if(state.game&&!lock){shuffle(state.game.tiles);selected=null;save();renderBoard();toast('已重新摆放，月饼状态保持不变')}},pair:()=>{if(!state.game||lock)return;let ts=state.game.tiles.filter(x=>!x.gone);for(let a of ts){let b=ts.find(x=>x.id!==a.id&&x.type===a.type&&(a.type!=='moon'||x.hp===a.hp));if(b){match(a,b);return}}checkBoardOutcome()},stash:()=>{if(selected===null){toast('先选中一块砖，再点击暂存');return}state.game.stashed=selected;save();renderBoard();toast('已暂存，点击它可继续配对')},slot:()=>toast('体验版保留槽位入口；正式效果复用游戏道具')};
document.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(b){if(b.disabled)return;actions[b.dataset.action]?.(b.dataset.id===undefined?undefined:Number(b.dataset.id));return}let t=e.target.closest('[data-tile]');if(t&&!blockClick)selectTile(+t.dataset.tile);let demo=e.target.closest('[data-demo]');if(demo)demoAction(demo.dataset.demo)});
$('#phone').addEventListener('pointerdown',e=>{let t=e.target.closest('[data-tile]');if(t&&!dialog)dragStart={id:+t.dataset.tile,x:e.clientX,y:e.clientY}});addEventListener('pointerup',e=>{if(!dragStart)return;let from=dragStart;dragStart=null;if(Math.hypot(e.clientX-from.x,e.clientY-from.y)<12)return;let to=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-tile]');if(to&&+to.dataset.tile!==from.id){selected=from.id;selectTile(+to.dataset.tile);blockClick=true;setTimeout(()=>blockClick=false,50)}});
function demoAction(a){if(lock)return;if(a==='reset'){exchangeScroll=0;state=fresh();save();login()}if(a==='login')login();if(a==='activity')navigate('activity');if(a==='success')settle(true,true);if(a==='failure')settle(false,true);if(a==='no-moves')demoNoMoves();if(a==='restart'){navigate('home');toast('已恢复本机记录，可继续挑战或领取奖励')}if(a==='target'){if(phase()!=='open'){toast('请切换到活动开放日期');return}state.total+=60;save();navigate('activity');toast('演示增加60个月饼，自由选择奖励兑换')} }
$('#date').addEventListener('change',e=>{if(lock)return;state.date=e.target.value;closeModal();save();if(phase()==='hidden'){state.game=null;navigate('home')}else if(page==='game'&&phase()!=='open'){state.game=null;navigate('activity')}else render();toast('演示日期已切换，月饼余额保留')});addEventListener('keydown',e=>{if(e.key==='Escape'){if(lock)return;if(dialog){closeModal();render()}else if(page==='game')pause();else if(page!=='home')navigate('home')}});
window.prototype={getState:()=>JSON.parse(JSON.stringify({page,dialog,...state})),demo:demoAction,navigate,selectTile,start,claim};
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_activity_prototype',description:'读取本机活动原型当前界面、进度与兑换状态。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>window.prototype.getState()})}catch{}}
function activityMarkup(){return `<div class="page activity exchange-page">
<img class="exchange-bg" src="assets/exchange/bg.png" alt=""><div class="exchange-hero" role="img" aria-label="月兔砖块小人与伙伴共度双节"></div>
<img class="exchange-title" src="assets/exchange/title.png" alt="好事成双"><div class="exchange-time">${leftTime()}</div><button class="exchange-help" data-action="rules" aria-label="活动说明">?</button>
<img class="exchange-board" src="assets/exchange/diban.png" alt=""><div class="exchange-balance"><img src="assets/exchange/block_shouji.png" alt="月饼"><span>拥有 <b>${state.total}</b> 个月饼</span></div>
<div class="exchange-scroll-hint">上下拖动，查看全部13款好礼</div>
<div class="exchange-list" tabindex="0" role="region" aria-label="奖励列表，可上下拖拽或滚动查看更多">${dates.map((d,i)=>{const owned=skins.includes(i)&&quantity(i)>0,status=owned?'已兑换':phase()==='ended'?'已结束':day()<d?'未开启':canClaim(i)?quantity(i)>0?'再兑换':'兑换':'月饼不足';return `<article class="exchange-card ${skins.includes(i)?'skin':'item'} quality-${qualities[i]}" data-reward="${i}"><span class="quality-label">${qualities[i]==='皮肤'?'限定皮肤':qualities[i]}</span><button class="exchange-prize" data-action="preview" data-id="${i}" aria-label="预览${names[i]}">${art(i)}</button><span class="exchange-name">${names[i]}</span>${skins.includes(i)?'<small class="exchange-limit">每款限兑1次</small>':quantity(i)>0?`<small class="exchange-owned">拥有×${quantity(i)}</small>`:''}<div class="exchange-info"><div class="exchange-date">${fmt(d)}</div><div class="exchange-price">${moonCost(prices[i])}</div><button class="exchange-button ${canClaim(i)?'available':'unavailable'}" data-action="exchange" data-id="${i}" ${canClaim(i)?'':'disabled'}>${status}</button></div></article>`}).join('')}</div>
<div class="exchange-bottom"><img class="exchange-foreground" src="assets/exchange/foreground.png" alt=""><button class="white-btn exchange-back" data-action="home" aria-label="返回主界面"></button><button class="white-btn exchange-start" data-action="start" ${canStart()?'':'disabled'}>${phase()==='preview'?'明日开启':phase()==='ended'?'活动已结束':state.game?'继续挑战':challengeUsed()?'今日已挑战':'开始挑战'}</button><p>${phase()==='ended'?'兑换已结束，已获得外观永久保留':challengeUsed()&&!state.game?'今天的挑战已结束，明天再来':'每天挑战1局 · 最多收集12个月饼'}</p></div></div>`;}
function confirmExchange(i){if(!canClaim(i)||lock)return;openModal(`<h2>兑换这份好礼？</h2><div class="reward-space">${art(i)}</div><h3>${names[i]}</h3><p>消耗 ${moonCost(prices[i])}<br>拥有 ${state.total} → 兑换后剩余 ${state.total-prices[i]}</p><small>${skins.includes(i)?'每款限兑1次，':''}兑换后放入图鉴</small><div class="confirm-actions"><button class="white-btn" data-action="close">取消</button><button class="white-btn" data-action="claim" data-id="${i}">确认兑换</button></div>`,'exchange-confirm');}
function showRules(){openModal(`<h2>好事成双 · 活动说明</h2><p><b>9月25日—10月7日</b><br>每天开放1款，共13款好礼。</p><p>每天可开启1局第二关，第一关不投放。<br>每局6对月饼，最多收集12个。<br>相同状态碰3次，消除一对收集2个。</p><p>成功、失败或确认放弃时，<br>已彻底消除的月饼结算入账。</p><p><b>月饼跨天保留，自由选奖，兑换扣费。</b><br>普通挂件4个，稀有10个，传说24个。<br>挂件可重复兑换，皮肤每款限兑1次。</p><small>10月7日结束收集和兑换；<br>10月8日至11日仅保留结束展示。<br>剩余月饼不自动换奖，已获得外观保留。</small><p><button class="white-btn" data-action="close">知道了</button></p>`,'exchange-rules');}

// Mouse dragging uses scaled design coordinates; touch keeps native momentum scrolling.
function bindRewardDrag(list){let drag=null,suppress=false;list.addEventListener('dragstart',e=>e.preventDefault());list.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0)return;drag={id:e.pointerId,y:e.clientY,top:list.scrollTop,moved:false};});list.addEventListener('pointermove',e=>{if(!drag)return;const dy=e.clientY-drag.y;if(Math.abs(dy)>6&&!drag.moved){drag.moved=true;list.setPointerCapture(e.pointerId);list.classList.add('dragging')}if(drag.moved){e.preventDefault();const scale=list.getBoundingClientRect().height/list.clientHeight;list.scrollTop=drag.top-dy/scale;exchangeScroll=list.scrollTop}});function end(){if(drag?.moved){suppress=true;setTimeout(()=>suppress=false,100)}drag=null;list.classList.remove('dragging')}list.addEventListener('pointerup',end);list.addEventListener('pointercancel',end);list.addEventListener('lostpointercapture',end);list.addEventListener('click',e=>{if(suppress){e.preventDefault();e.stopImmediatePropagation()}},true);list.addEventListener('scroll',()=>exchangeScroll=list.scrollTop,{passive:true});}
actions.rules=showRules;
actions.gallery=()=>openModal(`<h2>我的外观</h2>${state.claimed.length?`<div class="gallery-items">${state.claimed.map(i=>`<div class="gallery-item">${art(i)}${names[i]}<br>拥有×${quantity(i)}</div>`).join('')}</div>`:'<p>去好事成双收集第一份好礼吧</p>'}<button class="white-btn" data-action="activity">前往活动</button>`);
$('#date').innerHTML=[['2026-09-24','活动预热'],...dates.map((d,i)=>[d,names[i]]),['2026-10-08','结束展示'],['2026-10-11','展示最后一天'],['2026-10-12','入口下线']].map(([d,label])=>`<option value="${d}T12:00:00">${fmt(d)} · ${label}</option>`).join('');
const announcementDemo=document.createElement('button');announcementDemo.textContent='查看公告弹板';announcementDemo.addEventListener('click',showAnnouncement);$('.demo-buttons').append(announcementDemo);
$('.flow-rail [data-step="activity"]').textContent='自由兑换';$('.flow-rail [data-step="reward"]').textContent='获得新装';$('.flow-rail p').innerHTML='奖励按日期开放<br>月饼余额跨天保留<br>自主选择 · 兑换扣费';$('[data-demo="target"]').textContent='增加60个月饼';document.querySelectorAll('.state small')[1].textContent='月饼余额 / 已兑外观';resize();login();
